// grpc_client.rs — gRPC client wrapping the EdgePush service.
//
// Uses tonic for gRPC transport and prost for protobuf encoding.
// Proto types are generated by build.rs from clients/edge-tauri/proto/edge_push.proto.
//
// # MVP note
//
// Until build.rs proto generation is run (`cargo build`), the proto_gen module
// is stubs.  The stubs compile and allow Tauri to build, but gRPC calls will
// not function without a proto-compiled server.

use serde::{Deserialize, Serialize};
use tonic::transport::Channel;

// Include generated proto types (created by build.rs + tonic-build).
// Falls back to the stub module when proto hasn't been compiled yet.
#[cfg(feature = "proto_gen")]
pub mod edge_push {
    tonic::include_proto!("cardex.edge");
}

// ─── Public types (serde-compatible for Tauri command bridge) ─────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VehicleListing {
    pub vin: String,
    pub make: String,
    pub model: String,
    pub year: i32,
    pub price_cents: i32,
    pub currency: String,
    pub mileage_km: i32,
    pub fuel_type: String,
    pub transmission: String,
    pub color: String,
    pub source_url: String,
    #[serde(default)]
    pub image_urls: Vec<String>,
    #[serde(default)]
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PushSummary {
    pub accepted: i32,
    pub rejected: i32,
    pub errors: Vec<String>,
}

// ─── Client ──────────────────────────────────────────────────────────────────

#[derive(Clone)]
pub struct CardexEdgeClient {
    dealer_id: String,
    api_key: String,
    channel: Channel,
}

impl CardexEdgeClient {
    /// Connect to the Edge Push gRPC server.
    /// `server_addr` example: "https://edge.cardex.eu:50051"
    pub async fn connect(
        dealer_id: String,
        api_key: String,
        server_addr: String,
    ) -> Result<Self, tonic::transport::Error> {
        let channel = Channel::from_shared(server_addr)
            .expect("invalid server address")
            .connect()
            .await?;

        Ok(Self { dealer_id, api_key, channel })
    }

    /// Push a batch of listings to the server using the client-streaming RPC.
    pub async fn push_listings(
        &self,
        listings: Vec<VehicleListing>,
    ) -> Result<PushSummary, Box<dyn std::error::Error + Send + Sync>> {
        // Build the outbound stream.
        let dealer_id = self.dealer_id.clone();
        let api_key = self.api_key.clone();

        // Convert local VehicleListing to proto type.
        #[cfg(feature = "proto_gen")]
        {
            use edge_push::edge_push_client::EdgePushClient;
            use edge_push::{ListingBatch, VehicleListing as ProtoListing};

            let mut client = EdgePushClient::new(self.channel.clone());

            let batch = ListingBatch {
                dealer_id,
                api_key,
                timestamp_unix: std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs() as i64,
                listings: listings
                    .into_iter()
                    .map(|l| ProtoListing {
                        vin: l.vin,
                        make: l.make,
                        model: l.model,
                        year: l.year,
                        price_cents: l.price_cents,
                        currency: l.currency,
                        mileage_km: l.mileage_km,
                        fuel_type: l.fuel_type,
                        transmission: l.transmission,
                        color: l.color,
                        image_urls: l.image_urls,
                        description: l.description,
                        source_url: l.source_url,
                    })
                    .collect(),
            };

            let stream = tokio_stream::once(batch);
            let resp = client.push_listings(stream).await?.into_inner();

            return Ok(PushSummary {
                accepted: resp.accepted,
                rejected: resp.rejected,
                errors: resp
                    .rejections
                    .into_iter()
                    .map(|r| format!("{}: {}", r.vin, r.reason))
                    .collect(),
            });
        }

        // Stub path: proto_gen feature not enabled.
        #[cfg(not(feature = "proto_gen"))]
        {
            let _ = (dealer_id, api_key, listings);
            Err("proto_gen feature not enabled — run 'cargo build' to compile the proto".into())
        }
    }

    /// Send a heartbeat and return the server Unix timestamp.
    pub async fn heartbeat(
        &self,
    ) -> Result<i64, Box<dyn std::error::Error + Send + Sync>> {
        #[cfg(feature = "proto_gen")]
        {
            use edge_push::edge_push_client::EdgePushClient;
            use edge_push::HeartbeatRequest;

            let mut client = EdgePushClient::new(self.channel.clone());
            let resp = client
                .heartbeat(HeartbeatRequest {
                    dealer_id: self.dealer_id.clone(),
                })
                .await?
                .into_inner();
            return Ok(resp.server_time_unix);
        }

        #[cfg(not(feature = "proto_gen"))]
        Err("proto_gen feature not enabled".into())
    }
}
