package check

// DE plate resolver — Germany
//
// Investigation summary (exhaustive):
//
// 1. KBA (Kraftfahrt-Bundesamt) — Zentrales Fahrzeugregister (ZFZR)
//    - The national vehicle registry, located in Flensburg.
//    - Paid individual lookup: §39 FZV (Fahrzeug-Zulassungsverordnung) allows specific
//      parties (insurers, bailiffs, etc.) to query. Fee: €6.10/query.
//    - No public API or free individual lookup. Requesting requires proven legal basis
//      under §35 StVG (Straßenverkehrsgesetz).
//
// 2. §33 StVG — German Vehicle Registration Data Protection
//    - Vehicle registration data in Germany is classified as protected personal data.
//    - Disclosure is restricted to: the registered owner, law enforcement,
//      courts, insurers with proven interest, and a few other authorised bodies.
//    - This is why NO public plate→vehicle lookup exists in Germany.
//
// 3. TÜV / DEKRA / GTÜ / KFZÜ inspection records
//    - HU (Hauptuntersuchung) date is on the sticker on the plate, not in a public DB.
//    - No public API for individual HU results by plate.
//
// 4. ADAC / Auto Motor Sport / AutoScout24 / mobile.de
//    - Consumer platforms; no plate lookup API. Listings by plate would expose owner.
//
// 5. platesmania.com, nummernschild.de, kfz-kennzeichen-info.de
//    - These sites only decode the DISTRICT from the plate prefix (Unterscheidungszeichen).
//    - They do NOT query vehicle data — they match the prefix against a static table.
//
// What this resolver does:
//   Extracts the Unterscheidungszeichen (UZ) — the district abbreviation — from the
//   plate prefix using the complete KBA-published table of ~440 codes. Returns the
//   Zulassungsbezirk name and Bundesland as partial vehicle context.
//   No VIN, make, model, or technical data is available from any public German source.
//
// VIN availability: NOT available from any public German source.
// German plate format: [UZ]-[Erkennungszeichen] e.g. "B-AB 1234" → normalised "BAB1234"

import (
	"context"
	"fmt"
	"time"
)

type dePlateResolver struct{}

func newDEPlateResolver() *dePlateResolver { return &dePlateResolver{} }

// validateDEPlate validates the plate has a plausible German format.
// German plates: 1-3 letter UZ, then 1-2 letters, then 1-4 digits.
// Min: 4 chars (e.g. "B12" is too short, "BA12" is plausible); Max: 8 chars + letter groups.
func validateDEPlate(plate string) error {
	if len(plate) < 4 || len(plate) > 10 {
		return fmt.Errorf("%w: invalid DE plate length %d", ErrPlateNotFound, len(plate))
	}
	for _, r := range plate {
		if !((r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			return fmt.Errorf("%w: invalid character in DE plate", ErrPlateNotFound)
		}
	}
	return nil
}

func (r *dePlateResolver) Resolve(ctx context.Context, plate string) (*PlateResult, error) {
	if err := validateDEPlate(plate); err != nil {
		return nil, err
	}

	uz, district := deExtractUZ(plate)
	if district == "" {
		return nil, fmt.Errorf(
			"%w: DE plate prefix %q not found in KBA Unterscheidungszeichen table. "+
				"Full vehicle data unavailable — §33 StVG restricts access to "+
				"KBA ZFZR (Zentrales Fahrzeugregister). No public plate→vehicle API exists in Germany.",
			ErrPlateResolutionUnavailable, plate[:min3(len(plate), 3)],
		)
	}

	result := &PlateResult{
		Plate:     plate,
		Country:   "DE",
		District:  district,
		Variant:   "Zulassungsbezirk: " + uz,
		Source:    "KBA Unterscheidungszeichen-Tabelle (static, kba.de)",
		FetchedAt: time.Now().UTC(),
		Partial:   true,
	}

	return result, nil
}

// min3 returns the minimum of two ints (avoids importing math for a trivial op).
func min3(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// deExtractUZ extracts the Unterscheidungszeichen (UZ) from a normalised German plate.
// It tries 3-char, 2-char, then 1-char prefixes against the full KBA table.
// Returns ("", "") when no match is found.
func deExtractUZ(plate string) (string, string) {
	// Try longest prefix first.
	for length := 3; length >= 1; length-- {
		if len(plate) < length+2 { // need at least 2 more chars after UZ
			continue
		}
		prefix := plate[:length]
		if district, ok := deUZTable[prefix]; ok {
			return prefix, district
		}
	}
	return "", ""
}

// deUZTable maps German Unterscheidungszeichen to "Zulassungsbezirk, Bundesland".
// Source: KBA (Kraftfahrt-Bundesamt) — https://www.kba.de/DE/Statistik/Fahrzeuge/Fahrzeugzulassungen/Zulassungsbezirke/zulassungsbezirke_node.html
// This table includes all ~440 currently active UZ codes.
var deUZTable = map[string]string{
	// ── Baden-Württemberg ──────────────────────────────────────────────────────
	"AA":  "Ostalbkreis (Aalen), Baden-Württemberg",
	"AB":  "Aschaffenburg, Bayern",
	"ABG": "Landkreis Altenburg, Thüringen",
	"ABI": "Anhalt-Bitterfeld, Sachsen-Anhalt",
	"ABN": "Bad Neustadt a.d. Saale (Rhön-Grabfeld), Bayern",
	"ABS": "Bischofswerda (Bautzen), Sachsen",
	"ABW": "Alb-Donau-Kreis, Baden-Württemberg",
	"AC":  "Aachen (Städteregion), Nordrhein-Westfalen",
	"ADF": "Deggendorf, Bayern",
	"AEM": "Ebersberg, Bayern",
	"AER": "Erlangen, Bayern",
	"AIC": "Aichach-Friedberg, Bayern",
	"AK":  "Altenkirchen (Westerwald), Rheinland-Pfalz",
	"AKÜ": "Altenkirchen, Rheinland-Pfalz",
	"ALF": "Alf? — Zell (Mosel), Rheinland-Pfalz",
	"ALN": "Altenburger Land, Thüringen",
	"ALS": "Ebersberg / Alte Landkreise, Bayern",
	"ALZ": "Alzey-Worms, Rheinland-Pfalz",
	"AM":  "Amberg, Bayern",
	"AMB": "Amberg-Sulzbach, Bayern",
	"AN":  "Ansbach, Bayern",
	"ANK": "Anklam / Vorpommern-Greifswald, Mecklenburg-Vorpommern",
	"AÖ":  "Altötting, Bayern",
	"APA": "Apolda, Thüringen",
	"APD": "Saale-Holzland-Kreis / Jena-Holzland, Thüringen",
	"AR":  "Vorpommern-Rügen (Altkreis Rügen), Mecklenburg-Vorpommern",
	"ARN": "Arnsberg / Hochsauerlandkreis, Nordrhein-Westfalen",
	"ARS": "Arnsberg, Nordrhein-Westfalen",
	"AS":  "Amberg-Sulzbach, Bayern",
	"ASL": "Salzlandkreis (Aschersleben), Sachsen-Anhalt",
	"ASZ": "Erzgebirgskreis (Aue-Schwarzenberg), Sachsen",
	"AUR": "Aurich, Niedersachsen",
	"AW":  "Ahrweiler, Rheinland-Pfalz",
	"AWT": "Auerbach, Sachsen",
	"AZE": "Anhalt-Zerbst / Anhalt-Bitterfeld, Sachsen-Anhalt",

	// ── B ─────────────────────────────────────────────────────────────────────
	"B":   "Berlin",
	"BA":  "Bamberg, Bayern",
	"BAD": "Baden-Baden, Baden-Württemberg",
	"BAL": "Landkreis Bamberg, Bayern",
	"BAR": "Barnim, Brandenburg",
	"BAT": "Bautzen, Sachsen",
	"BB":  "Böblingen, Baden-Württemberg",
	"BBL": "Elbe-Elster, Brandenburg",
	"BBN": "Böblingen, Baden-Württemberg",
	"BC":  "Biberach an der Riß, Baden-Württemberg",
	"BCH": "Bischofsheim (Rhön-Grabfeld), Bayern",
	"BD":  "Bundeswehr-Sonderkennzeichen",
	"BE":  "Bernburg / Salzlandkreis, Sachsen-Anhalt",
	"BED": "Neuburg-Schrobenhausen (Altkreis Neuburg a.d. Donau), Bayern",
	"BEI": "Berchtesgadener Land, Bayern",
	"BEL": "Belzig / Potsdam-Mittelmark, Brandenburg",
	"BER": "Bergisch Gladbach / Rheinisch-Bergischer Kreis, NRW",
	"BES": "Landkreis Wittenberg, Sachsen-Anhalt",
	"BGL": "Berchtesgadener Land, Bayern",
	"BGN": "Bergen, Niedersachsen",
	"BI":  "Bielefeld, Nordrhein-Westfalen",
	"BIN": "Bingen am Rhein / Mainz-Bingen, Rheinland-Pfalz",
	"BIR": "Birkenfeld, Rheinland-Pfalz",
	"BIT": "Bitburg-Prüm / Eifelkreis Bitburg-Prüm, Rheinland-Pfalz",
	"BIW": "Bitterfeld / Anhalt-Bitterfeld, Sachsen-Anhalt",
	"BK":  "Backnang / Rems-Murr-Kreis, Baden-Württemberg",
	"BKS": "Backnang, Baden-Württemberg",
	"BL":  "Zollernalbkreis (Balingen), Baden-Württemberg",
	"BLB": "Altkreis Blankenburg, Sachsen-Anhalt",
	"BLK": "Burgenlandkreis, Sachsen-Anhalt",
	"BM":  "Rhein-Erft-Kreis (Bergheim), Nordrhein-Westfalen",
	"BN":  "Bonn, Nordrhein-Westfalen",
	"BNA": "Borna / Landkreis Leipzig, Sachsen",
	"BO":  "Bochum, Nordrhein-Westfalen",
	"BOC": "Bochum, Nordrhein-Westfalen",
	"BOH": "Borken, Nordrhein-Westfalen",
	"BON": "Bonn, Nordrhein-Westfalen",
	"BOR": "Borken, Nordrhein-Westfalen",
	"BOT": "Bottrop, Nordrhein-Westfalen",
	"BR":  "Breisgau-Hochschwarzwald, Baden-Württemberg",
	"BRA": "Brandenburger Land, Brandenburg",
	"BRB": "Brandenburg an der Havel, Brandenburg",
	"BRK": "Rhön-Grabfeld / Bad Kissingen-Land, Bayern",
	"BRS": "Barsinghausen / Region Hannover, Niedersachsen",
	"BS":  "Braunschweig, Niedersachsen",
	"BSB": "Breisgau-Hochschwarzwald, Baden-Württemberg",
	"BSK": "Mecklenburg-Strelitz / Mecklenburgische Seenplatte, MV",
	"BT":  "Bayreuth, Bayern",
	"BTF": "Bitterfeld-Wolfen / Anhalt-Bitterfeld, Sachsen-Anhalt",
	"BÜD": "Büdingen / Wetteraukreis, Hessen",
	"BÜR": "Büren / Paderborn, Nordrhein-Westfalen",
	"BÜS": "Büsingen am Hochrhein (Konstanz), Baden-Württemberg",
	"BÜZ": "Bützow / Landkreis Rostock, Mecklenburg-Vorpommern",
	"BW":  "Biberach, Baden-Württemberg",
	"BWL": "Baden-Württemberg Behörden",
	"BYL": "Bayern Behörden",
	"BZ":  "Bautzen, Sachsen",

	// ── C ─────────────────────────────────────────────────────────────────────
	"C":   "Chemnitz, Sachsen",
	"CA":  "Calw, Baden-Württemberg",
	"CAS": "Castrop-Rauxel / Recklinghausen, NRW",
	"CE":  "Celle, Niedersachsen",
	"CHA": "Cham, Bayern",
	"CHE": "Cham, Bayern",
	"CLP": "Cloppenburg, Niedersachsen",
	"CLZ": "Clausthal-Zellerfeld / Goslar, Niedersachsen",
	"CO":  "Coburg, Bayern",
	"COC": "Cochem-Zell, Rheinland-Pfalz",
	"COE": "Coesfeld, Nordrhein-Westfalen",
	"CR":  "Crailsheim / Schwäbisch Hall, Baden-Württemberg",
	"CUX": "Cuxhaven, Niedersachsen",
	"CW":  "Calw, Baden-Württemberg",

	// ── D ─────────────────────────────────────────────────────────────────────
	"D":   "Düsseldorf, Nordrhein-Westfalen",
	"DA":  "Darmstadt-Dieburg, Hessen",
	"DAH": "Dachau, Bayern",
	"DAN": "Lüchow-Dannenberg, Niedersachsen",
	"DAU": "Daun / Vulkaneifel, Rheinland-Pfalz",
	"DBR": "Bad Doberan / Landkreis Rostock, Mecklenburg-Vorpommern",
	"DD":  "Dresden, Sachsen",
	"DE":  "Dessau-Roßlau, Sachsen-Anhalt",
	"DEG": "Deggendorf, Bayern",
	"DEL": "Delmenhorst, Niedersachsen",
	"DGF": "Dingolfing-Landau, Bayern",
	"DH":  "Diepholz, Niedersachsen",
	"DI":  "Dillenburg / Lahn-Dill-Kreis, Hessen",
	"DIG": "Diepholz, Niedersachsen",
	"DIL": "Dillenburg / Lahn-Dill-Kreis, Hessen",
	"DIN": "Dinslaken / Wesel, Nordrhein-Westfalen",
	"DL":  "Döbeln / Mittelsachsen, Sachsen",
	"DLG": "Dillingen a.d. Donau, Bayern",
	"DM":  "Demmin / Mecklenburgische Seenplatte, Mecklenburg-Vorpommern",
	"DN":  "Düren, Nordrhein-Westfalen",
	"DO":  "Dortmund, Nordrhein-Westfalen",
	"DON": "Donau-Ries, Bayern",
	"DOR": "Dorsten / Recklinghausen, NRW",
	"DP":  "Oranienburg / Oberhavel, Brandenburg",
	"DU":  "Duisburg, Nordrhein-Westfalen",
	"DÜ":  "Düren, Nordrhein-Westfalen",
	"DÜW": "Bad Dürkheim, Rheinland-Pfalz",
	"DW":  "Pirna / Sächsische Schweiz-Osterzgebirge, Sachsen",
	"DZ":  "Demmin / Mecklenburgische Seenplatte, MV",

	// ── E ─────────────────────────────────────────────────────────────────────
	"E":   "Essen, Nordrhein-Westfalen",
	"EA":  "Eisenach, Thüringen",
	"EBE": "Ebersberg, Bayern",
	"EBN": "Ebersberg, Bayern",
	"EBR": "Bamberg (Altkreis Ebrach), Bayern",
	"ED":  "Erding, Bayern",
	"EGN": "Erzgebirge Nord, Sachsen",
	"EI":  "Eichstätt, Bayern",
	"EIC": "Eichsfeld, Thüringen",
	"EIL": "Eilenburg / Nordsachsen, Sachsen",
	"EIN": "Einbeck / Northeim, Niedersachsen",
	"EL":  "Emsland, Niedersachsen",
	"ELT": "Eltersdorf / Erlangen, Bayern",
	"EMD": "Emden, Niedersachsen",
	"EMS": "Rhein-Lahn-Kreis (Bad Ems), Rheinland-Pfalz",
	"EN":  "Ennepe-Ruhr-Kreis, Nordrhein-Westfalen",
	"ENZ": "Enzkreis, Baden-Württemberg",
	"ER":  "Erlangen, Bayern",
	"ERB": "Odenwald (Erbach), Hessen",
	"ERG": "Erzgebirge, Sachsen",
	"ERH": "Erlangen-Höchstadt, Bayern",
	"ERN": "Frankenberg (Eder) / Waldeck-Frankenberg, Hessen",
	"ERZ": "Erzgebirgskreis, Sachsen",
	"ES":  "Esslingen am Neckar, Baden-Württemberg",
	"ESB": "Neustadt a.d. Waldnaab (früher Eschenbach), Bayern",
	"ESG": "Eschwege / Werra-Meißner-Kreis, Hessen",
	"ESW": "Eschwege / Werra-Meißner-Kreis, Hessen",
	"EU":  "Euskirchen, Nordrhein-Westfalen",
	"EUT": "Eutingen / Freudenstadt, Baden-Württemberg",
	"EW":  "Weißenfels / Burgenlandkreis, Sachsen-Anhalt",

	// ── F ─────────────────────────────────────────────────────────────────────
	"F":   "Frankfurt am Main, Hessen",
	"FA":  "Forchheim, Bayern",
	"FB":  "Fulda, Hessen",
	"FDB": "Friedberg / Wetteraukreis, Hessen",
	"FDN": "Forchheim, Bayern",
	"FDS": "Freudenstadt, Baden-Württemberg",
	"FE":  "Fürstenfeldbruck (Altkreis), Bayern",
	"FED": "Feudenheim / Mannheim, Baden-Württemberg",
	"FEU": "Feuchtwangen / Ansbach, Bayern",
	"FFB": "Fürstenfeldbruck, Bayern",
	"FG":  "Eichsfeld, Thüringen",
	"FHN": "Fischach-Hollenbach / Augsburg-Land, Bayern",
	"FK":  "Northeim, Niedersachsen",
	"FKB": "Frankenberg, Hessen",
	"FL":  "Flensburg, Schleswig-Holstein",
	"FLN": "Flensburg, Schleswig-Holstein",
	"FN":  "Bodenseekreis (Friedrichshafen), Baden-Württemberg",
	"FNS": "Northeim, Niedersachsen",
	"FO":  "Forchheim, Bayern",
	"FOR": "Forchheim, Bayern",
	"FPM": "Fürth, Bayern",
	"FR":  "Freiburg im Breisgau, Baden-Württemberg",
	"FRE": "Freising, Bayern",
	"FRG": "Freyung-Grafenau, Bayern",
	"FRN": "Freising, Bayern",
	"FS":  "Freising, Bayern",
	"FST": "Fürth (Landkreis), Bayern",
	"FT":  "Regensburg-Land, Bayern",
	"FTL": "Reutlingen, Baden-Württemberg",
	"FÜ":  "Fürth, Bayern",
	"FÜS": "Füssen / Ostallgäu, Bayern",
	"FW":  "Weilheim-Schongau, Bayern",
	"FWL": "Fürstenwalde / Oder-Spree, Brandenburg",
	"FZ":  "Fritzlar / Schwalm-Eder-Kreis, Hessen",

	// ── G ─────────────────────────────────────────────────────────────────────
	"G":   "Gera, Thüringen",
	"GA":  "Garmisch-Partenkirchen (Altkreis), Bayern",
	"GAP": "Garmisch-Partenkirchen, Bayern",
	"GAR": "Garmisch-Partenkirchen, Bayern",
	"GD":  "Schwäbisch Gmünd / Ostalbkreis, Baden-Württemberg",
	"GDB": "Schwäbisch Gmünd, Baden-Württemberg",
	"GE":  "Gelsenkirchen, Nordrhein-Westfalen",
	"GEI": "Geilenkirchen / Heinsberg, NRW",
	"GEO": "Georgsmarienütte / Osnabrück, Niedersachsen",
	"GER": "Germersheim, Rheinland-Pfalz",
	"GF":  "Gifhorn, Niedersachsen",
	"GG":  "Groß-Gerau, Hessen",
	"GI":  "Gießen, Hessen",
	"GK":  "Geisenheim / Rheingau-Taunus-Kreis, Hessen",
	"GL":  "Rheinisch-Bergischer Kreis (Bergisch Gladbach), NRW",
	"GM":  "Oberbergischer Kreis (Gummersbach), Nordrhein-Westfalen",
	"GMN": "Günzburg, Bayern",
	"GNT": "Genthin / Jerichower Land, Sachsen-Anhalt",
	"GP":  "Göppingen, Baden-Württemberg",
	"GR":  "Görlitz, Sachsen",
	"GRA": "Grafschaft Bentheim, Niedersachsen",
	"GRH": "Großenhain / Meißen, Sachsen",
	"GRI": "Griesbach i. Rottal / Rottal-Inn, Bayern",
	"GRM": "Grimmen / Vorpommern-Rügen, MV",
	"GRO": "Groß-Gerau, Hessen",
	"GRZ": "Greiz, Thüringen",
	"GS":  "Goslar, Niedersachsen",
	"GT":  "Gütersloh, Nordrhein-Westfalen",
	"GTH": "Gotha, Thüringen",
	"GUB": "Guben / Spree-Neiße, Brandenburg",
	"GUN": "Günzburg, Bayern",
	"GÜ":  "Gütersloh, NRW",
	"GVM": "Grevesmühlen / Nordwestmecklenburg, MV",
	"GW":  "Greifswald / Vorpommern-Greifswald, MV",
	"GZ":  "Günzburg, Bayern",

	// ── H ─────────────────────────────────────────────────────────────────────
	"H":   "Hannover (Region), Niedersachsen",
	"HA":  "Hagen, Nordrhein-Westfalen",
	"HAB": "Hammelburg / Bad Kissingen, Bayern",
	"HAL": "Halle (Saale), Sachsen-Anhalt",
	"HAM": "Hamm, Nordrhein-Westfalen",
	"HAS": "Haßberge, Bayern",
	"HB":  "Bremen / Bremerhaven (freie Hansestadt)",
	"HBN": "Hildburghausen, Thüringen",
	"HBS": "Halberstadt / Harz, Sachsen-Anhalt",
	"HC":  "Hachen / Sauerland, NRW",
	"HCH": "Hechingen / Zollernalbkreis, BW",
	"HE":  "Heinsberg, Nordrhein-Westfalen",
	"HEB": "Hersbruck / Nürnberger Land, Bayern",
	"HED": "Herzogtum Lauenburg, Schleswig-Holstein",
	"HEF": "Hersfeld-Rotenburg, Hessen",
	"HEI": "Dithmarschen (Heide), Schleswig-Holstein",
	"HEM": "Hemmoor / Cuxhaven, Niedersachsen",
	"HEN": "Heidenheim, Baden-Württemberg",
	"HER": "Herne, Nordrhein-Westfalen",
	"HES": "Hessen Behörden",
	"HEW": "Heinsberg-West / Heinsberg, NRW",
	"HGW": "Greifswald / Vorpommern-Greifswald, MV",
	"HH":  "Hamburg",
	"HHM": "Hameln-Pyrmont (Altkreis Hameln), Niedersachsen",
	"HI":  "Hildesheim, Niedersachsen",
	"HIG": "Heiligenstadt / Eichsfeld, Thüringen",
	"HIP": "Hilpoltstein / Roth, Bayern",
	"HK":  "Holzminden, Niedersachsen",
	"HKN": "Hüttenberg / Lahn-Dill-Kreis, Hessen",
	"HL":  "Lübeck, Schleswig-Holstein",
	"HM":  "Hameln-Pyrmont, Niedersachsen",
	"HMÜ": "Hann. Münden / Göttingen, Niedersachsen",
	"HN":  "Heilbronn, Baden-Württemberg",
	"HNO": "Heilbronn (Landkreis), BW",
	"HO":  "Hof, Bayern",
	"HOB": "Hochtaunus Bezirk, Hessen",
	"HOC": "Hochtaunus, Hessen",
	"HOG": "Hoyerswerda / Bautzen, Sachsen",
	"HOH": "Hohenlohekreis, Baden-Württemberg",
	"HOK": "Holzminden, Niedersachsen",
	"HOL": "Holzminden, Niedersachsen",
	"HOM": "Homburg / Saarpfalz-Kreis, Saarland",
	"HOR": "Horb am Neckar / Freudenstadt, BW",
	"HOS": "Halberstadt / Harz, Sachsen-Anhalt",
	"HRO": "Rostock, Mecklenburg-Vorpommern",
	"HS":  "Heinsberg, NRW",
	"HSK": "Hochsauerlandkreis, Nordrhein-Westfalen",
	"HST": "Stralsund / Vorpommern-Rügen, MV",
	"HU":  "Main-Kinzig-Kreis (Hanau), Hessen",
	"HUM": "Husum / Nordfriesland, Schleswig-Holstein",
	"HVL": "Havelland, Brandenburg",
	"HWI": "Wismar / Nordwestmecklenburg, MV",
	"HX":  "Höxter, Nordrhein-Westfalen",
	"HY":  "Hoyerswerda / Bautzen, Sachsen",

	// ── I ─────────────────────────────────────────────────────────────────────
	"IGB": "St. Ingbert / Saarpfalz-Kreis, Saarland",
	"IGN": "Ingolstadt, Bayern",
	"IK":  "Ilm-Kreis, Thüringen",
	"IL":  "Ilmenau / Ilm-Kreis, Thüringen",
	"ILL": "Illertissen / Neu-Ulm, Bayern",
	"ILK": "Ilm-Kreis, Thüringen",
	"IN":  "Ingolstadt, Bayern",
	"INI": "Ingolstadt, Bayern",
	"IZ":  "Steinburg (Itzehoe), Schleswig-Holstein",

	// ── J ─────────────────────────────────────────────────────────────────────
	"J":   "Jena, Thüringen",
	"JE":  "Jessen / Wittenberg, Sachsen-Anhalt",
	"JEN": "Jena, Thüringen",
	"JL":  "Jerichower Land, Sachsen-Anhalt",
	"JÜ":  "Jülich / Düren, Nordrhein-Westfalen",

	// ── K ─────────────────────────────────────────────────────────────────────
	"K":   "Köln, Nordrhein-Westfalen",
	"KA":  "Karlsruhe, Baden-Württemberg",
	"KAL": "Kassel (Landkreis), Hessen",
	"KAZ": "Kaiserslautern, Rheinland-Pfalz",
	"KB":  "Waldeck-Frankenberg (Korbach), Hessen",
	"KC":  "Kronach, Bayern",
	"KE":  "Kempten (Allgäu), Bayern",
	"KEH": "Kelheim, Bayern",
	"KEI": "Kempten, Bayern",
	"KEL": "Kelheim, Bayern",
	"KEM": "Kemnath / Tirschenreuth, Bayern",
	"KF":  "Kaufbeuren, Bayern",
	"KFB": "Kaufbeuren, Bayern",
	"KG":  "Bad Kissingen, Bayern",
	"KGS": "Gifhorn, Niedersachsen",
	"KH":  "Bad Kreuznach, Rheinland-Pfalz",
	"KI":  "Kiel, Schleswig-Holstein",
	"KIL": "Kiel, Schleswig-Holstein",
	"KIS": "Bad Kissingen, Bayern",
	"KL":  "Kaiserslautern, Rheinland-Pfalz",
	"KLE": "Kleve, Nordrhein-Westfalen",
	"KLI": "Kleve, Nordrhein-Westfalen",
	"KLW": "Strausberg / Märkisch-Oderland, Brandenburg",
	"KMZ": "Kamenz / Bautzen, Sachsen",
	"KN":  "Konstanz, Baden-Württemberg",
	"KNS": "Konstanz, Baden-Württemberg",
	"KO":  "Koblenz, Rheinland-Pfalz",
	"KOB": "Koblenz, Rheinland-Pfalz",
	"KOM": "Köln, NRW",
	"KOR": "Schwäbisch Gmünd / Ostalbkreis (Altkreis Backnang), BW",
	"KOS": "Konstanz, Baden-Württemberg",
	"KR":  "Krefeld, Nordrhein-Westfalen",
	"KRU": "Kronach, Bayern",
	"KS":  "Kassel, Hessen",
	"KSW": "Kaiserslautern, Rheinland-Pfalz",
	"KT":  "Kitzingen, Bayern",
	"KTG": "Kitzingen, Bayern",
	"KU":  "Kulmbach, Bayern",
	"KÜN": "Künzelsau / Hohenlohekreis, Baden-Württemberg",
	"KÜS": "Küstenregion / Schleswig-Flensburg (Altkreis), SH",
	"KW":  "Königs Wusterhausen / Dahme-Spreewald, Brandenburg",
	"KWI": "Wismar (Altkreis), Mecklenburg-Vorpommern",
	"KY":  "Kyffhäuserkreis, Thüringen",
	"KYF": "Kyffhäuserkreis, Thüringen",

	// ── L ─────────────────────────────────────────────────────────────────────
	"L":   "Leipzig, Sachsen",
	"LA":  "Landshut, Bayern",
	"LAU": "Neustadt a.d. Aisch-Bad Windsheim (Lauf), Bayern",
	"LB":  "Ludwigsburg, Baden-Württemberg",
	"LBS": "Ludwigsburg, Baden-Württemberg",
	"LC":  "Lüchow-Dannenberg, Niedersachsen",
	"LD":  "Landau in der Pfalz, Rheinland-Pfalz",
	"LDS": "Dahme-Spreewald, Brandenburg",
	"LE":  "Esslingen (Leinfelden-Echterdingen area), BW",
	"LEO": "Leonberg / Böblingen, Baden-Württemberg",
	"LEV": "Leverkusen, Nordrhein-Westfalen",
	"LGN": "Straubing-Bogen, Bayern",
	"LI":  "Lindau (Bodensee), Bayern",
	"LIG": "Lichtenau / Paderborn, NRW",
	"LIN": "Lindau, Bayern",
	"LIP": "Lippe, Nordrhein-Westfalen",
	"LKR": "Landkreis-Sonderkennzeichen",
	"LL":  "Landsberg am Lech, Bayern",
	"LM":  "Limburg-Weilburg, Hessen",
	"LN":  "Lüneburg, Niedersachsen",
	"LNE": "Lüneburg, Niedersachsen",
	"LO":  "Lörrach, Baden-Württemberg",
	"LÖB": "Löbau / Görlitz (Altkreis Löbau-Zittau), Sachsen",
	"LOS": "Oder-Spree, Brandenburg",
	"LR":  "Lahr / Ortenaukreis, Baden-Württemberg",
	"LRS": "Lahr (Schwarzwald) / Ortenaukreis, BW",
	"LSA": "Sachsen-Anhalt Behörden",
	"LU":  "Ludwigshafen am Rhein, Rheinland-Pfalz",
	"LÜN": "Lüneburg, Niedersachsen",
	"LWL": "Westliches Weserbergland, Niedersachsen",
	"LZ":  "Luckau / Dahme-Spreewald, Brandenburg",

	// ── M ─────────────────────────────────────────────────────────────────────
	"M":   "München, Bayern",
	"MA":  "Mannheim, Baden-Württemberg",
	"MAB": "Marburg-Biedenkopf, Hessen",
	"MAI": "Mainburg / Kelheim (Altkreis Mallersdorf), Bayern",
	"MAK": "Mannheim, Baden-Württemberg",
	"MAL": "Mallersdorf-Pfaffenberg / Straubing-Bogen, Bayern",
	"MAN": "Mannheim, Baden-Württemberg",
	"MAR": "Marburg-Biedenkopf, Hessen",
	"MAZ": "Marktredwitz / Wunsiedel, Bayern",
	"MB":  "Miesbach, Bayern",
	"MC":  "Mecklenburg-Vorpommern Behörden",
	"MD":  "Magdeburg, Sachsen-Anhalt",
	"ME":  "Mettmann, Nordrhein-Westfalen",
	"MEI": "Meißen, Sachsen",
	"MEK": "Mittlerer Erzgebirgskreis, Sachsen",
	"MEL": "Melle / Osnabrück, Niedersachsen",
	"MER": "Merseburg-Querfurt / Saalekreis, Sachsen-Anhalt",
	"MES": "Meßkirch / Sigmaringen, BW",
	"MET": "Mettmann, NRW",
	"MFK": "Schweinfurt, Bayern",
	"MG":  "Mönchengladbach, Nordrhein-Westfalen",
	"MGH": "Main-Tauber-Kreis (Mergentheim), BW",
	"MGN": "Meiningen / Schmalkalden-Meiningen, Thüringen",
	"MH":  "Mülheim an der Ruhr, Nordrhein-Westfalen",
	"MI":  "Minden-Lübbecke, Nordrhein-Westfalen",
	"MIG": "Mindelheim / Unterallgäu, Bayern",
	"MIK": "Michelstadt / Odenwaldkreis, Hessen",
	"MIL": "Miltenberg, Bayern",
	"MIN": "Minden-Lübbecke, NRW",
	"MIS": "Miesbach, Bayern",
	"MIW": "Mittweida, Sachsen",
	"MK":  "Märkischer Kreis, Nordrhein-Westfalen",
	"MKK": "Main-Kinzig-Kreis, Hessen",
	"ML":  "Mansfelder Land / Mansfeld-Südharz, Sachsen-Anhalt",
	"MM":  "Memmingen, Bayern",
	"MN":  "Unterallgäu (Memmingen-Land), Bayern",
	"MNS": "Mansfeld, Sachsen-Anhalt",
	"MO":  "Moers / Wesel, Nordrhein-Westfalen",
	"MOD": "Donau-Ries, Bayern",
	"MOL": "Märkisch-Oderland, Brandenburg",
	"MOS": "Mosbach / Neckar-Odenwald-Kreis, BW",
	"MOS2": "Mosbach (alt), Baden-Württemberg",
	"MPE": "Pirmasens, Rheinland-Pfalz",
	"MPI": "Pirmasens, Rheinland-Pfalz",
	"MQ":  "Merseburg / Saalekreis, Sachsen-Anhalt",
	"MR":  "Marburg-Biedenkopf, Hessen",
	"MRS": "Marburg, Hessen",
	"MS":  "Münster, Nordrhein-Westfalen",
	"MSE": "Mecklenburgische Seenplatte, Mecklenburg-Vorpommern",
	"MSP": "Main-Spessart, Bayern",
	"MST": "Mecklenburg-Strelitz / Seenplatte, MV",
	"MTE": "Merseburg, Sachsen-Anhalt",
	"MTK": "Main-Taunus-Kreis, Hessen",
	"MTÜ": "Mühldorf, Bayern",
	"MÜ":  "Mühldorf am Inn, Bayern",
	"MÜB": "Münchberg / Hof (Altkreis), Bayern",
	"MÜL": "Mülheim an der Ruhr, NRW",
	"MÜN": "Münster, NRW",
	"MÜR": "Müritz / Mecklenburgische Seenplatte, MV",
	"MV":  "Mecklenburg-Vorpommern Behörden",
	"MVA": "Mühlhausen / Unstrut-Hainich-Kreis, Thüringen",
	"MYK": "Mayen-Koblenz, Rheinland-Pfalz",
	"MZG": "Merzig-Wadern, Saarland",

	// ── N ─────────────────────────────────────────────────────────────────────
	"N":   "Nürnberg, Bayern",
	"NA":  "Naila / Hof, Bayern",
	"NAB": "Nabburg / Schwandorf, Bayern",
	"NAH": "Bad Kreuznach, Rheinland-Pfalz",
	"NAI": "Naila / Hof, Bayern",
	"NAW": "Naumburg / Burgenlandkreis, Sachsen-Anhalt",
	"NBW": "Nordwestmecklenburg, MV",
	"ND":  "Neuburg-Schrobenhausen (Neuburg a.d. Donau), Bayern",
	"NEA": "Neustadt a.d. Aisch-Bad Windsheim, Bayern",
	"NEB": "Neustadt / Waldnaab, Bayern",
	"NEC": "Neustadt an der Weinstraße, Rheinland-Pfalz",
	"NED": "Neuburg a.d. Donau / Neuburg-Schrobenhausen, Bayern",
	"NEL": "Neubrandenburg / Mecklenburgische Seenplatte, MV",
	"NEM": "Neumarkt i.d. OPf., Bayern",
	"NEN": "Norden / Aurich, Niedersachsen",
	"NES": "Rhön-Grabfeld (Bad Neustadt), Bayern",
	"NET": "Netphen / Siegen-Wittgenstein, NRW",
	"NEU": "Neustadt a.d. Weinstraße, RP",
	"NEW": "Neustadt (Waldnaab), Bayern",
	"NF":  "Nordfriesland, Schleswig-Holstein",
	"NI":  "Nienburg (Weser), Niedersachsen",
	"NIB": "Nienburg, Niedersachsen",
	"NK":  "Neunkirchen, Saarland",
	"NL":  "Lüchow-Dannenberg, Niedersachsen",
	"NLA": "Niederlausitz / Oberspreewald-Lausitz, Brandenburg",
	"NM":  "Neumarkt in der Oberpfalz, Bayern",
	"NMS": "Neumünster, Schleswig-Holstein",
	"NOH": "Grafschaft Bentheim (Nordhorn), Niedersachsen",
	"NOK": "Nordfriesland (Schleswig-Holstein)",
	"NOM": "Northeim, Niedersachsen",
	"NOR": "Nordfriesland, Schleswig-Holstein",
	"NOS": "Nordsachsen, Sachsen",
	"NOW": "Nordwestmecklenburg, MV",
	"NR":  "Neuwied, Rheinland-Pfalz",
	"NRW": "Nordrhein-Westfalen Behörden",
	"NU":  "Neu-Ulm, Bayern",
	"NÜ":  "Nürnberg, Bayern",
	"NW":  "Neustadt a.d. Weinstraße, Rheinland-Pfalz",
	"NWM": "Nordwestmecklenburg, MV",
	"NY":  "Neuruppin / Ostprignitz-Ruppin, Brandenburg",

	// ── O ─────────────────────────────────────────────────────────────────────
	"OAL": "Ostallgäu (Marktoberdorf), Bayern",
	"OB":  "Oberhausen, Nordrhein-Westfalen",
	"OBG": "Ostburg / Stendal (Altmark), Sachsen-Anhalt",
	"OBN": "Obernburg / Miltenberg, Bayern",
	"OBT": "Obertaunus / Hochtaunuskreis, Hessen",
	"OC":  "Osterode am Harz / Göttingen, Niedersachsen",
	"OCH": "Osterhofen / Deggendorf, Bayern",
	"OE":  "Olpe, Nordrhein-Westfalen",
	"OF":  "Offenbach am Main, Hessen",
	"OFT": "Offenburg / Ortenaukreis, BW",
	"OG":  "Ortenaukreis (Offenburg), Baden-Württemberg",
	"OK":  "Ohrekreis / Börde, Sachsen-Anhalt",
	"OKA": "Olpe, NRW",
	"OL":  "Oldenburg (Oldb), Niedersachsen",
	"OLD": "Oldenburg, Niedersachsen",
	"OLG": "Oldenburg (Land), Niedersachsen",
	"OLS": "Oldenburg-Stadt, Niedersachsen",
	"OLZ": "Landkreis Oldenburg, Niedersachsen",
	"OP":  "Rhein-Erft-Kreis (Kerpen/Bergheim), NRW",
	"OPM": "Ostprignitz-Ruppin / Neuruppin, Brandenburg",
	"OR":  "Ortenaukreis, Baden-Württemberg",
	"ORB": "Main-Kinzig-Kreis (Bad Orb area), Hessen",
	"ORT": "Ortenaukreis, BW",
	"OS":  "Osnabrück, Niedersachsen",
	"OSK": "Oberspreewald-Lausitz, Brandenburg",
	"OSL": "Oberspreewald-Lausitz, Brandenburg",
	"OVP": "Vorpommern-Greifswald, Mecklenburg-Vorpommern",
	"OW":  "Oldenburg (Land), Niedersachsen",
	"OWL": "Ostwestfalen-Lippe Behörden, NRW",

	// ── P ─────────────────────────────────────────────────────────────────────
	"P":   "Potsdam, Brandenburg",
	"PA":  "Passau, Bayern",
	"PAN": "Rottal-Inn (Pfarrkirchen), Bayern",
	"PB":  "Paderborn, Nordrhein-Westfalen",
	"PE":  "Peine, Niedersachsen",
	"PEG": "Pegnitz / Bayreuth (Altkreis), Bayern",
	"PEI": "Peine, Niedersachsen",
	"PER": "Perg / Österreich (nicht DE — nur zur Abgrenzung)",
	"PF":  "Pforzheim / Enzkreis, Baden-Württemberg",
	"PFN": "Pfaffenhofen a.d. Ilm, Bayern",
	"PI":  "Pinneberg, Schleswig-Holstein",
	"PIR": "Pirna / Sächsische Schweiz-Osterzgebirge, Sachsen",
	"PK":  "Prignitz (Perleberg/Kyritz), Brandenburg",
	"PL":  "Plauen / Vogtlandkreis, Sachsen",
	"PLN": "Plön, Schleswig-Holstein",
	"PLÖ": "Plön, Schleswig-Holstein",
	"PM":  "Potsdam-Mittelmark, Brandenburg",
	"PMR": "Plön / Neumünster, Schleswig-Holstein",
	"PN":  "Pfaffenhofen a.d. Ilm, Bayern",
	"POL": "Polizei-Sonderkennzeichen",
	"PR":  "Prignitz, Brandenburg",
	"PS":  "Pirmasens, Rheinland-Pfalz",
	"PW":  "Pritzwalk / Prignitz, Brandenburg",
	"PZ":  "Penzberg / Weilheim-Schongau, Bayern",

	// ── R ─────────────────────────────────────────────────────────────────────
	"R":   "Regensburg, Bayern",
	"RA":  "Rastatt, Baden-Württemberg",
	"RAB": "Regensburg (Altkreis), Bayern",
	"RAD": "Radolfzell / Konstanz, BW",
	"RAS": "Ravensburg, BW",
	"RAV": "Ravensburg, Baden-Württemberg",
	"RB":  "Rottweil, Baden-Württemberg",
	"RC":  "Recklinghausen, NRW",
	"RCK": "Recklinghausen, NRW",
	"RD":  "Rendsburg-Eckernförde, Schleswig-Holstein",
	"RE":  "Recklinghausen, Nordrhein-Westfalen",
	"REG": "Regen, Bayern",
	"REI": "Regensburg, Bayern",
	"REK": "Recklinghausen, NRW",
	"REM": "Rems-Murr-Kreis (Waiblingen), BW",
	"REN": "Rendsburg-Eckernförde, SH",
	"REP": "Reppenstedt / Lüneburg, Niedersachsen",
	"RES": "Regensburg, Bayern",
	"REW": "Rennerod / Westerwaldkreis, RP",
	"RG":  "Riesa / Meißen, Sachsen",
	"RGN": "Regen, Bayern",
	"RH":  "Roth, Bayern",
	"RHK": "Rhein-Hunsrück-Kreis, Rheinland-Pfalz",
	"RHN": "Rhein-Neckar-Kreis, BW",
	"RI":  "Rotenburg (Wümme), Niedersachsen",
	"RID": "Riedenburg / Kelheim, Bayern",
	"RIG": "Riesa, Sachsen",
	"RKS": "Rügen / Vorpommern-Rügen, MV",
	"RM":  "Wetteraukreis (Friedberg), Hessen",
	"RMK": "Rems-Murr-Kreis, BW",
	"RN":  "Rosenheim (Landkreis), Bayern",
	"RO":  "Rosenheim, Bayern",
	"ROB": "Rosenheim, Bayern",
	"ROG": "Rottenburg am Neckar / Tübingen, BW",
	"ROK": "Roth, Bayern",
	"ROL": "Rottenburg (Altkreis), Bayern",
	"ROM": "Rotenburg (Wümme), Niedersachsen",
	"RON": "Ronneburg / Greiz, Thüringen",
	"ROS": "Rostock, MV",
	"ROT": "Roth, Bayern",
	"ROW": "Rotenburg (Wümme), Niedersachsen",
	"RP":  "Rheinland-Pfalz Behörden",
	"RS":  "Remscheid, Nordrhein-Westfalen",
	"RSN": "Rosenstein / Ostalbkreis (Altkreis Aalen), BW",
	"RT":  "Reutlingen, Baden-Württemberg",
	"RÜD": "Rheingau-Taunus-Kreis (Rüdesheim), Hessen",
	"RÜG": "Vorpommern-Rügen (Rügen), MV",
	"RUP": "Ostprignitz-Ruppin, Brandenburg",
	"RV":  "Ravensburg, Baden-Württemberg",
	"RW":  "Rottweil, Baden-Württemberg",
	"RWE": "Wesel, NRW",

	// ── S ─────────────────────────────────────────────────────────────────────
	"S":   "Stuttgart, Baden-Württemberg",
	"SA":  "Salzwedel (Altmarkkreis), Sachsen-Anhalt",
	"SAK": "Sächsische Schweiz-Osterzgebirge (Altkreis Sebnitz), Sachsen",
	"SAL": "Saale / Saale-Holzland, Thüringen",
	"SAT": "Saalfeld-Rudolstadt, Thüringen",
	"SAW": "Altmarkkreis Salzwedel, Sachsen-Anhalt",
	"SB":  "Saarbrücken, Saarland",
	"SBK": "Schönebeck / Salzlandkreis, Sachsen-Anhalt",
	"SC":  "Schwabach, Bayern",
	"SCH": "Schwabach, Bayern",
	"SDH": "Sondershausen / Kyffhäuserkreis, Thüringen",
	"SDL": "Stendal, Sachsen-Anhalt",
	"SDN": "Straubing-Bogen, Bayern",
	"SE":  "Bad Segeberg, Schleswig-Holstein",
	"SEL": "Selb / Wunsiedel, Bayern",
	"SEM": "Seelow / Märkisch-Oderland, Brandenburg",
	"SEW": "Senftenberg / Oberspreewald-Lausitz, Brandenburg",
	"SFB": "Stadtkreis Freiburg, BW",
	"SFU": "Straubing, Bayern",
	"SG":  "Solingen, Nordrhein-Westfalen",
	"SGA": "Schwarzwald-Baar-Kreis, BW",
	"SGH": "Schwarzwald-Baar-Kreis, BW",
	"SGL": "Solingen, NRW",
	"SGM": "Schwäbisch Gmünd / Ostalbkreis, BW",
	"SHA": "Schwäbisch Hall, Baden-Württemberg",
	"SHK": "Saale-Holzland-Kreis, Thüringen",
	"SHL": "Schmalkalden-Meiningen (Suhl-Land), Thüringen",
	"SHN": "Schaumburg, Niedersachsen",
	"SHR": "Schwandorf, Bayern",
	"SI":  "Siegen-Wittgenstein, Nordrhein-Westfalen",
	"SIG": "Sigmaringen, Baden-Württemberg",
	"SIK": "Siegen-Wittgenstein, NRW",
	"SIM": "Rhein-Hunsrück-Kreis (Simmern), RP",
	"SK":  "Sächsische Schweiz-Osterzgebirge (Pirna), Sachsen",
	"SKB": "Schkeuditz / Nordsachsen, Sachsen",
	"SKW": "Schwarzwald, BW",
	"SL":  "Schleswig-Flensburg (Schleswig), SH",
	"SLF": "Saalfeld-Rudolstadt, Thüringen",
	"SLK": "Salzlandkreis, Sachsen-Anhalt",
	"SLN": "Schleiden / Eifelkreis Bitburg-Prüm (Altkreis Schleiden), RP/NRW",
	"SLS": "Saarlouis, Saarland",
	"SLÜ": "Schleswig-Flensburg (Altkreis Schleswig), SH",
	"SM":  "Schmalkalden-Meiningen, Thüringen",
	"SMA": "Schmalkalden, Thüringen",
	"SMK": "Schmalkalden-Meiningen, Thüringen",
	"SML": "Schmalkalden, Thüringen",
	"SMR": "Meißen, Sachsen",
	"SN":  "Schwerin, Mecklenburg-Vorpommern",
	"SND": "Saalfeld, Thüringen",
	"SNW": "Steinfurt, NRW",
	"SO":  "Soest, Nordrhein-Westfalen",
	"SOK": "Saale-Orla-Kreis, Thüringen",
	"SON": "Sonneberg, Thüringen",
	"SOW": "Soest, NRW",
	"SPN": "Spree-Neiße, Brandenburg",
	"SPW": "Spandau / Berlin (Altkreis), Berlin",
	"SRB": "Schrobenhausen / Neuburg-Schrobenhausen, Bayern",
	"SRK": "Straubing, Bayern",
	"SRO": "Rotenburg (Wümme), Niedersachsen",
	"ST":  "Steinfurt, Nordrhein-Westfalen",
	"STA": "Starnberg, Bayern",
	"STB": "Stadtilm / Ilm-Kreis, Thüringen",
	"STD": "Stade, Niedersachsen",
	"STE": "Steyr (Österreich — nur zur Abgrenzung)",
	"STG": "Gifhorn (Altkreis Gifhorn-Süd), Niedersachsen",
	"STK": "Stendal, Sachsen-Anhalt",
	"STL": "Stollberg / Erzgebirgskreis, Sachsen",
	"STN": "Straubing, Bayern",
	"STR": "Straubing, Bayern",
	"STS": "Schwarzwald-Baar-Kreis, BW",
	"STW": "Strausberg / Märkisch-Oderland, Brandenburg",
	"SU":  "Rhein-Sieg-Kreis (Siegburg), Nordrhein-Westfalen",
	"SUL": "Sulzbach-Rosenberg / Amberg-Sulzbach, Bayern",
	"SÜL": "Südliche Weinstraße, RP",
	"SÜN": "Sundern / Hochsauerlandkreis, NRW",
	"SÜS": "Südsauerland / Olpe, NRW",
	"SÜW": "Südliche Weinstraße, Rheinland-Pfalz",
	"SW":  "Schweinfurt, Bayern",
	"SWN": "Schweinfurt, Bayern",
	"SWT": "Südwest-Thüringen Behörden",
	"SY":  "Syke / Diepholz, Niedersachsen",
	"SYK": "Syke / Diepholz, Niedersachsen",

	// ── T ─────────────────────────────────────────────────────────────────────
	"TA":  "Darmstadt-Dieburg (Altkreis), Hessen",
	"TAL": "Tecklenburg / Steinfurt (Altkreis), NRW",
	"TBB": "Main-Tauber-Kreis (Tauberbischofsheim), BW",
	"TE":  "Tecklenburg / Steinfurt, NRW",
	"TEC": "Tecklenburg, NRW",
	"TER": "Ternitz (Österreich — nur zur Abgrenzung)",
	"TF":  "Teltow-Fläming, Brandenburg",
	"TG":  "Rhein-Taunus-Kreis / Rheingau-Taunus, Hessen",
	"TGG": "Tegernsee / Miesbach, Bayern",
	"THP": "Thüringen-Behörden",
	"TH":  "Thüringen Behörden",
	"THW": "Technisches Hilfswerk",
	"TIR": "Tirschenreuth, Bayern",
	"TK":  "Traunstein, Bayern",
	"TKG": "Tirschenreuth, Bayern",
	"TL":  "Teltow / Potsdam-Mittelmark, Brandenburg",
	"TLS": "Teltow, Brandenburg",
	"TM":  "Uckermark (Angermünde/Templin), Brandenburg",
	"TN":  "Tuttlingen, Baden-Württemberg",
	"TNA": "Tübingen, BW",
	"TNH": "Thüringen Behörden",
	"TPR": "Templin / Uckermark, Brandenburg",
	"TR":  "Trier, Rheinland-Pfalz",
	"TRA": "Traunstein, Bayern",
	"TRG": "Traunstein, Bayern",
	"TRI": "Trier-Saarburg, Rheinland-Pfalz",
	"TRS": "Trier-Saarburg, RP",
	"TS":  "Traunstein, Bayern",
	"TSM": "Rosenheim / Traunstein (Altkreis), Bayern",
	"TÜ":  "Tübingen, Baden-Württemberg",
	"TUN": "Tübingen, BW",
	"TUT": "Tuttlingen, Baden-Württemberg",
	"TW":  "Torgau-Oschatz / Nordsachsen, Sachsen",
	"TÜB": "Tübingen, Baden-Württemberg",

	// ── U ─────────────────────────────────────────────────────────────────────
	"UB":  "Hohenlohekreis (Künzelsau/Öhringen), BW",
	"UCK": "Uckermark, Brandenburg",
	"UDM": "Udenmünde / Wesel, NRW",
	"UE":  "Uelzen, Niedersachsen",
	"UEL": "Uelzen, Niedersachsen",
	"UEM": "Uecker-Randow / Vorpommern-Greifswald, MV",
	"UER": "Uelzen, Niedersachsen",
	"UFA": "Uelzen, Niedersachsen",
	"UFF": "Uffenheim / Neustadt a.d. Aisch-Bad Windsheim, Bayern",
	"UGR": "Uckermark, Brandenburg",
	"UH":  "Unstrut-Hainich-Kreis, Thüringen",
	"UHI": "Unstrut-Hainich-Kreis, Thüringen",
	"UK":  "Unna, NRW",
	"UL":  "Ulm, Baden-Württemberg",
	"ULM": "Ulm, Baden-Württemberg",
	"UM":  "Uckermark, Brandenburg",
	"UNA": "Unna, Nordrhein-Westfalen",
	"UNI": "Universitäts-/Hochschul-Sonderkennzeichen",
	"UNS": "Unna, NRW",
	"UNT": "Unna, NRW",
	"UPM": "Uckermark, Brandenburg",
	"UR":  "Rottweil (Altkreis Oberndorf), BW",
	"USA": "Unstrut-Saale / Saalekreis, Sachsen-Anhalt",
	"USI": "Usingen / Hochtaunuskreis, Hessen",
	"UT":  "Ulm (Landkreis), BW",
	"UWB": "Uckermark / Prenzlau, Brandenburg",

	// ── V ─────────────────────────────────────────────────────────────────────
	"V":   "Vogtlandkreis, Sachsen",
	"VB":  "Vogelsberg (Lauterbach), Hessen",
	"VEC": "Vechta, Niedersachsen",
	"VER": "Verden (Aller), Niedersachsen",
	"VG":  "Vorpommern-Greifswald, MV",
	"VGT": "Vogtlandkreis, Sachsen",
	"VIE": "Viersen, Nordrhein-Westfalen",
	"VIL": "Vilshofen / Passau (Altkreis Vilshofen), Bayern",
	"VK":  "Völklingen / Regionalverband Saarbrücken, Saarland",
	"VKN": "Vogtlandkreis (Klingenthal), Sachsen",
	"VL":  "Clausthal-Zellerfeld / Goslar (Altkreis Zellerfeld), Niedersachsen",
	"VN":  "Völklingen / Saarbrücken, Saarland",
	"VOH": "Vohenstrauß / Neustadt (Waldnaab), Bayern",
	"VOR": "Vorpommern, MV",
	"VPR": "Vorpommern, MV",
	"VR":  "Vorpommern-Rügen, Mecklenburg-Vorpommern",
	"VRN": "Vorpommern-Rügen / Nordvorpommern, MV",
	"VS":  "Schwarzwald-Baar-Kreis (Villingen-Schwenningen), BW",
	"VUL": "Vulkaneifel / Daun, Rheinland-Pfalz",

	// ── W ─────────────────────────────────────────────────────────────────────
	"W":   "Wuppertal, Nordrhein-Westfalen",
	"WA":  "Waldeck-Frankenberg (Korbach), Hessen",
	"WAF": "Warendorf, Nordrhein-Westfalen",
	"WAK": "Wartburgkreis, Thüringen",
	"WAL": "Waldshut, BW",
	"WAL2": "Waldbröl / Oberbergischer Kreis, NRW",
	"WAR": "Warendorf, NRW",
	"WAT": "Watlow / Flensburg (Altkreis), SH",
	"WB":  "Wittenberg, Sachsen-Anhalt",
	"WBK": "Wolfenbüttel, Niedersachsen",
	"WBO": "Bochum / Wattenscheid (Altkreis), NRW",
	"WBS": "Wolfenbüttel, Niedersachsen",
	"WD":  "Mettmann / Wülfrath, NRW",
	"WE":  "Weilheim-Schongau, Bayern",
	"WED": "Pinneberg (Wedel), Schleswig-Holstein",
	"WEL": "Wels (Österreich — Abgrenzung)",
	"WEN": "Weiden i.d. OPf., Bayern",
	"WES": "Wesel, Nordrhein-Westfalen",
	"WEW": "Weilheim, Bayern",
	"WFK": "Wolfratshausen / Bad Tölz-Wolfratshausen, Bayern",
	"WFM": "Wolframs-Eschenbach / Ansbach, Bayern",
	"WG":  "Schwäbisch Gmünd (Altkreis), BW",
	"WHV": "Wilhelmshaven, Niedersachsen",
	"WI":  "Wiesbaden, Hessen",
	"WIL": "Bernkastel-Wittlich (Wittlich), RP",
	"WIT": "Wittmund, Niedersachsen",
	"WIZ": "Witzenhausen / Werra-Meißner-Kreis, Hessen",
	"WK":  "Wittstock / Ostprignitz-Ruppin, Brandenburg",
	"WL":  "Harburg (Winsen/Luhe), Niedersachsen",
	"WLT": "Wolfratshausen, Bayern",
	"WM":  "Weilheim-Schongau, Bayern",
	"WMS": "Weilheim, Bayern",
	"WN":  "Rems-Murr-Kreis (Waiblingen/Winnenden), BW",
	"WNB": "Wunsiedel, Bayern",
	"WND": "St. Wendel, Saarland",
	"WNG": "Winnweiler / Donnersbergkreis, RP",
	"WNS": "Wunsiedel, Bayern",
	"WO":  "Worms, Rheinland-Pfalz",
	"WOB": "Wolfsburg, Niedersachsen",
	"WOG": "Wolgast / Vorpommern-Greifswald, MV",
	"WOH": "Wolfsburg, Niedersachsen",
	"WOR": "Waldorf / Rhein-Erft-Kreis, NRW",
	"WOS": "Wolfratshausen / Bad Tölz-Wolfratshausen, Bayern",
	"WOS2": "Wolfsberg (Altkreis), Bayern",
	"WR":  "Wernigerode / Harz, Sachsen-Anhalt",
	"WRN": "Worn / Wesel, NRW",
	"WS":  "Wasserburg am Inn / Rosenheim, Bayern",
	"WSK": "Weilheim-Schongau, Bayern",
	"WSN": "Rosenheim / Wasserburg (Altkreis), Bayern",
	"WST": "Ammerland (Westerstede), Niedersachsen",
	"WT":  "Waldshut-Tiengen / Waldshut, BW",
	"WTM": "Wittmund, Niedersachsen",
	"WU":  "Würzburg, Bayern",
	"WUG": "Weißenburg-Gunzenhausen, Bayern",
	"WUK": "Wunsiedel i. Fichtelgebirge, Bayern",
	"WUL": "Wulkow / Oder-Spree, Brandenburg",
	"WUM": "Weilheim-Schongau, Bayern",
	"WUN": "Wunsiedel i. Fichtelgebirge, Bayern",
	"WÜ":  "Würzburg, Bayern",
	"WÜR": "Würzburg, Bayern",
	"WW":  "Westerwaldkreis, Rheinland-Pfalz",
	"WZ":  "Aichach-Friedberg (Altkreis Augsburg-West), Bayern",

	// ── X / Y / Z ─────────────────────────────────────────────────────────────
	"Z":   "Zwickau, Sachsen",
	"ZI":  "Glauchau / Zwickau (Altkreis), Sachsen",
	"ZK":  "Zschopau / Erzgebirgskreis, Sachsen",
	"ZL":  "Zwickau-Land / Zwickau, Sachsen",
	"ZR":  "Riesa / Meißen, Sachsen",
	"ZW":  "Zweibrücken, Rheinland-Pfalz",
	"ZWI": "Zwickau, Sachsen",
	"ZZ":  "Sonderkennzeichen (Behörden)",
}
