// cardex-cli — terminal-first buyer interface for the CARDEX vehicle index.
//
// Commands:
//
//	cardex search [flags]                  — query vehicle_record with filters
//	cardex show <id>                       — full details + quality score breakdown
//	cardex stats                           — aggregate counts and confidence metrics
//	cardex review list [--status]          — list manual review queue items
//	cardex review show <id>                — show review item with vehicle context
//	cardex review approve <id>             — approve a pending listing
//	cardex review reject <id> --reason ""  — reject a pending listing with reason
//
// The CLI reads from the same SQLite database written by the pipeline
// (discovery-service → extraction-service → quality-service).
//
// AI Act Art. 50(2) compliance: when a vehicle description was generated by a
// local LLM, the terminal renders a visible "[AI]" badge next to the
// description field. This satisfies the user-facing disclosure requirement
// of EU Reg. 2024/1689 Art. 50(1) (deployer must inform users interacting
// with AI-generated content).
//
// Build:
//
//	make cli
//	# or: cd frontend/terminal && GOWORK=off go build -o cardex-cli ./cmd/cardex/
package main

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
	"github.com/spf13/cobra"
	_ "modernc.org/sqlite"
)

// ── Styles ────────────────────────────────────────────────────────────────────

var (
	styleHeader  = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("33"))
	styleBold    = lipgloss.NewStyle().Bold(true)
	styleGreen   = lipgloss.NewStyle().Foreground(lipgloss.Color("82"))
	styleYellow  = lipgloss.NewStyle().Foreground(lipgloss.Color("220"))
	styleRed     = lipgloss.NewStyle().Foreground(lipgloss.Color("196"))
	styleDim     = lipgloss.NewStyle().Faint(true)
	styleBorder  = lipgloss.NewStyle().
			Border(lipgloss.NormalBorder()).
			BorderForeground(lipgloss.Color("240")).
			Padding(0, 1)

	// styleAIBadge renders the "[AI]" disclosure badge required by EU AI Act
	// Art. 50(1) — visible indicator that the description was generated by an LLM.
	styleAIBadge = lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("0")).
			Background(lipgloss.Color("220")).
			Padding(0, 1)
)

// ── DB helpers ────────────────────────────────────────────────────────────────

func openDB(path string) (*sql.DB, error) {
	if path == "" {
		path = defaultDBPath()
	}
	db, err := sql.Open("sqlite", path+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		return nil, fmt.Errorf("open db %q: %w", path, err)
	}
	db.SetMaxOpenConns(1)
	return db, nil
}

func defaultDBPath() string {
	if p := os.Getenv("CARDEX_DB_PATH"); p != "" {
		return p
	}
	return filepath.Join(".", "data", "discovery.db")
}

// ── Commands ──────────────────────────────────────────────────────────────────

var (
	flagDBPath   string
	flagCountry  string
	flagMake     string
	flagModel    string
	flagYearMin  int
	flagYearMax  int
	flagPriceMin int
	flagPriceMax int
	flagKmMax    int
	flagScore    float64
	flagLimit    int
	flagPage     int
)

func newRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:   "cardex",
		Short: "CARDEX vehicle index CLI",
		Long: `cardex — terminal-first buyer interface for the CARDEX used-car index.

Reads from the shared SQLite database written by the CARDEX pipeline.
Set CARDEX_DB_PATH or pass --db to point at your database file.`,
		SilenceUsage: true,
	}
	root.PersistentFlags().StringVar(&flagDBPath, "db", "", "path to SQLite database (env: CARDEX_DB_PATH)")

	root.AddCommand(newSearchCmd())
	root.AddCommand(newShowCmd())
	root.AddCommand(newStatsCmd())
	root.AddCommand(newReviewCmd())
	return root
}

// ── cardex search ─────────────────────────────────────────────────────────────

func newSearchCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "search",
		Short: "Search vehicle listings",
		Example: `  cardex search --country DE --make BMW --model "Serie 3" --year-min 2020 --price-max 25000
  cardex search --make Renault --km-max 80000 --score 70`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			db, err := openDB(flagDBPath)
			if err != nil {
				return err
			}
			defer db.Close()
			return runSearch(db)
		},
	}
	cmd.Flags().StringVar(&flagCountry, "country", "", "ISO-3166-1 country code (DE, FR, ES, NL, BE, CH)")
	cmd.Flags().StringVar(&flagMake, "make", "", "vehicle make (case-insensitive)")
	cmd.Flags().StringVar(&flagModel, "model", "", "vehicle model (case-insensitive, partial match)")
	cmd.Flags().IntVar(&flagYearMin, "year-min", 0, "minimum model year (inclusive)")
	cmd.Flags().IntVar(&flagYearMax, "year-max", 0, "maximum model year (inclusive)")
	cmd.Flags().IntVar(&flagPriceMin, "price-min", 0, "minimum price in EUR")
	cmd.Flags().IntVar(&flagPriceMax, "price-max", 0, "maximum price in EUR")
	cmd.Flags().IntVar(&flagKmMax, "km-max", 0, "maximum odometer reading in km")
	cmd.Flags().Float64Var(&flagScore, "score", 0, "minimum composite quality score (0–100)")
	cmd.Flags().IntVar(&flagLimit, "limit", 25, "results per page")
	cmd.Flags().IntVar(&flagPage, "page", 1, "page number (1-based)")
	return cmd
}

func runSearch(db *sql.DB) error {
	query, args := buildSearchQuery()
	rows, err := db.Query(query, args...)
	if err != nil {
		return fmt.Errorf("search: %w", err)
	}
	defer rows.Close()

	type row struct {
		id, make_, model, vin, country string
		year, mileage, priceNet        int
		score                          float64
		url                            string
	}

	var results []row
	for rows.Next() {
		var r row
		var priceNet sql.NullInt64
		var score sql.NullFloat64
		var url sql.NullString
		if err := rows.Scan(&r.id, &r.make_, &r.model, &r.vin, &r.country,
			&r.year, &r.mileage, &priceNet, &score, &url); err != nil {
			return err
		}
		r.priceNet = int(priceNet.Int64)
		r.score = score.Float64
		r.url = url.String
		results = append(results, r)
	}
	if err := rows.Err(); err != nil {
		return err
	}

	if len(results) == 0 {
		fmt.Println(styleDim.Render("No listings match your filters."))
		return nil
	}

	// ── Header row ──
	hdr := fmt.Sprintf("%-26s %-12s %-18s %5s %8s %8s %6s  %s",
		"ID", "COUNTRY/MAKE", "MODEL", "YEAR", "KM", "PRICE€", "SCORE", "URL")
	fmt.Println(styleHeader.Render(hdr))
	fmt.Println(strings.Repeat("─", 100))

	for _, r := range results {
		scoreStr := scoreStyle(r.score)
		priceStr := fmt.Sprintf("%8d", r.priceNet)
		urlShort := r.url
		if len(urlShort) > 40 {
			urlShort = urlShort[:37] + "..."
		}
		line := fmt.Sprintf("%-26s %-12s %-18s %5d %8d %s %s  %s",
			r.id, r.country+"/"+r.make_, r.model,
			r.year, r.mileage, priceStr, scoreStr, styleDim.Render(urlShort))
		fmt.Println(line)
	}
	fmt.Printf("\n%s\n", styleDim.Render(fmt.Sprintf("Page %d — %d result(s)  (--page / --limit to paginate)", flagPage, len(results))))
	return nil
}

func buildSearchQuery() (string, []any) {
	var conds []string
	var args []any

	if flagCountry != "" {
		conds = append(conds, "UPPER(de.country_code) = UPPER(?)")
		args = append(args, flagCountry)
	}
	if flagMake != "" {
		conds = append(conds, "UPPER(vr.make_canonical) = UPPER(?)")
		args = append(args, flagMake)
	}
	if flagModel != "" {
		conds = append(conds, "UPPER(vr.model_canonical) LIKE UPPER(?)")
		args = append(args, "%"+flagModel+"%")
	}
	if flagYearMin > 0 {
		conds = append(conds, "vr.year >= ?")
		args = append(args, flagYearMin)
	}
	if flagYearMax > 0 {
		conds = append(conds, "vr.year <= ?")
		args = append(args, flagYearMax)
	}
	if flagPriceMin > 0 {
		conds = append(conds, "vr.price_gross_eur >= ?")
		args = append(args, flagPriceMin)
	}
	if flagPriceMax > 0 {
		conds = append(conds, "vr.price_gross_eur <= ?")
		args = append(args, flagPriceMax)
	}
	if flagKmMax > 0 {
		conds = append(conds, "vr.mileage_km <= ?")
		args = append(args, flagKmMax)
	}
	if flagScore > 0 {
		conds = append(conds, "vr.confidence_score >= ?")
		args = append(args, flagScore/100.0)
	}

	where := ""
	if len(conds) > 0 {
		where = "WHERE " + strings.Join(conds, " AND ")
	}

	offset := (flagPage - 1) * flagLimit
	query := fmt.Sprintf(`
		SELECT
			vr.vehicle_id,
			COALESCE(vr.make_canonical, ''),
			COALESCE(vr.model_canonical, ''),
			COALESCE(vr.vin, ''),
			COALESCE(de.country_code, ''),
			COALESCE(vr.year, 0),
			COALESCE(vr.mileage_km, 0),
			CAST(COALESCE(vr.price_gross_eur, 0) AS INTEGER),
			COALESCE(vr.confidence_score, 0.0),
			COALESCE(vr.source_url, '')
		FROM vehicle_record vr
		LEFT JOIN dealer_entity de ON de.dealer_id = vr.dealer_id
		%s
		ORDER BY vr.indexed_at DESC
		LIMIT ? OFFSET ?`, where)

	args = append(args, flagLimit, offset)
	return query, args
}

// ── cardex show <id> ──────────────────────────────────────────────────────────

func newShowCmd() *cobra.Command {
	return &cobra.Command{
		Use:     "show <vehicle-id>",
		Short:   "Show full details and quality score breakdown for a listing",
		Args:    cobra.ExactArgs(1),
		Example: `  cardex show 01ARZ3NDEKTSV4RRFFQ69G5FAV`,
		RunE: func(_ *cobra.Command, args []string) error {
			db, err := openDB(flagDBPath)
			if err != nil {
				return err
			}
			defer db.Close()
			return runShow(db, args[0])
		},
	}
}

func runShow(db *sql.DB, id string) error {
	row := db.QueryRow(`
		SELECT
			vr.vehicle_id, vr.vin,
			COALESCE(vr.make_canonical,''), COALESCE(vr.model_canonical,''),
			COALESCE(vr.year,0), COALESCE(vr.mileage_km,0),
			COALESCE(vr.fuel_type,''), COALESCE(vr.transmission,''),
			COALESCE(vr.body_type,''), COALESCE(vr.color,''),
			CAST(COALESCE(vr.price_net_eur,0) AS INTEGER),
			CAST(COALESCE(vr.price_gross_eur,0) AS INTEGER),
			COALESCE(vr.source_url,''),
			COALESCE(vr.confidence_score,0.0),
			COALESCE(de.country_code,''),
			COALESCE(de.canonical_name,''),
			COALESCE(vr.indexed_at,''),
			COALESCE(vr.description,'')
		FROM vehicle_record vr
		LEFT JOIN dealer_entity de ON de.dealer_id = vr.dealer_id
		WHERE vr.vehicle_id = ?`, id)

	var (
		vid, vin, make_, model_, fuel, trans, body, color_, url, country, dealer, indexedAt string
		description                                                                           string
		year, mileage, priceNet, priceGross                                                  int
		score                                                                                float64
	)
	if err := row.Scan(&vid, &vin, &make_, &model_, &year, &mileage,
		&fuel, &trans, &body, &color_, &priceNet, &priceGross,
		&url, &score, &country, &dealer, &indexedAt, &description); err != nil {
		if err == sql.ErrNoRows {
			return fmt.Errorf("vehicle %q not found", id)
		}
		return err
	}

	// ── Detect AI-generated description via V11 evidence ──
	// The quality pipeline stores V11 evidence as JSON in validation_result.evidence.
	// We check for the presence of ai_generated_model evidence to determine if the
	// description was produced by an LLM — AI Act Art.50(1) requires a visible indicator.
	aiModel := ""
	aiLang := ""
	_ = db.QueryRow(`
		SELECT
			COALESCE(json_extract(evidence,'$.ai_generated_model'),''),
			COALESCE(json_extract(evidence,'$.ai_generated_lang'),'')
		FROM validation_result
		WHERE vehicle_id = ? AND validator_id = 'V11'`, id).Scan(&aiModel, &aiLang)
	isAIGenerated := aiModel != ""

	// ── Build description line with optional AI badge ──
	descLine := description
	if descLine == "" {
		descLine = styleDim.Render("(no description)")
	}
	if isAIGenerated {
		badge := styleAIBadge.Render(" AI ")
		descLine = badge + " " + descLine +
			styleDim.Render(fmt.Sprintf("  [model: %s, lang: %s]", aiModel, aiLang))
	}


	// ── Detail panel ──
	fmt.Println()
	fmt.Println(styleBorder.Render(
		styleHeader.Render("VEHICLE DETAIL") + "\n\n" +
			field("ID", vid) +
			field("VIN", vin) +
			field("Make/Model", make_+" "+model_) +
			field("Year", strconv.Itoa(year)) +
			field("Mileage", fmt.Sprintf("%d km", mileage)) +
			field("Fuel/Gearbox", fuel+" / "+trans) +
			field("Body/Color", body+" / "+color_) +
			field("Price (net)", fmt.Sprintf("€%d", priceNet)) +
			field("Price (gross)", fmt.Sprintf("€%d", priceGross)) +
			field("Country", country) +
			field("Dealer", dealer) +
			field("Source URL", url) +
			field("Quality score", scoreStyle(score*100)) +
			field("Indexed at", indexedAt) +
			field("Description", descLine),
	))

	// ── Quality validator breakdown ──
	valRows, err := db.Query(`
		SELECT validator_id, pass, severity, COALESCE(issue,'')
		FROM validation_result
		WHERE vehicle_id = ?
		ORDER BY validator_id`, id)
	if err != nil {
		return err
	}
	defer valRows.Close()

	var validators []string
	for valRows.Next() {
		var vid2, sev, issue string
		var pass bool
		if err := valRows.Scan(&vid2, &pass, &sev, &issue); err != nil {
			return err
		}
		mark := styleGreen.Render("✓")
		if !pass {
			if sev == "CRITICAL" {
				mark = styleRed.Render("✗")
			} else {
				mark = styleYellow.Render("⚠")
			}
		}
		line := fmt.Sprintf("  %s %s", mark, styleBold.Render(vid2))
		if issue != "" {
			line += styleDim.Render(" — "+issue)
		}
		validators = append(validators, line)
	}
	if len(validators) > 0 {
		fmt.Println("\n" + styleHeader.Render("QUALITY VALIDATORS"))
		for _, v := range validators {
			fmt.Println(v)
		}
	}
	fmt.Println()
	return nil
}

// ── cardex stats ──────────────────────────────────────────────────────────────

func newStatsCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "stats",
		Short: "Show aggregate pipeline statistics",
		RunE: func(_ *cobra.Command, _ []string) error {
			db, err := openDB(flagDBPath)
			if err != nil {
				return err
			}
			defer db.Close()
			return runStats(db)
		},
	}
}

func runStats(db *sql.DB) error {
	type countryStat struct {
		country string
		count   int
		avgKm   float64
		avgEUR  float64
	}

	rows, err := db.Query(`
		SELECT
			COALESCE(de.country_code, 'UNKNOWN') AS country,
			COUNT(*) AS cnt,
			AVG(COALESCE(vr.mileage_km, 0)) AS avg_km,
			AVG(COALESCE(vr.price_gross_eur, 0)) AS avg_eur
		FROM vehicle_record vr
		LEFT JOIN dealer_entity de ON de.dealer_id = vr.dealer_id
		GROUP BY country
		ORDER BY cnt DESC`)
	if err != nil {
		return fmt.Errorf("stats: %w", err)
	}
	defer rows.Close()

	var stats []countryStat
	var total int
	for rows.Next() {
		var s countryStat
		if err := rows.Scan(&s.country, &s.count, &s.avgKm, &s.avgEUR); err != nil {
			return err
		}
		stats = append(stats, s)
		total += s.count
	}
	if err := rows.Err(); err != nil {
		return err
	}

	var dealers int
	db.QueryRow(`SELECT COUNT(*) FROM dealer_entity WHERE status='ACTIVE'`).Scan(&dealers) //nolint:errcheck

	var avgScore float64
	db.QueryRow(`SELECT AVG(confidence_score) FROM vehicle_record WHERE confidence_score > 0`).Scan(&avgScore) //nolint:errcheck

	fmt.Println()
	fmt.Println(styleHeader.Render("CARDEX PIPELINE STATS"))
	fmt.Printf("  %s %s\n", styleBold.Render("Generated:"), time.Now().Format("2006-01-02 15:04:05 MST"))
	fmt.Println()
	fmt.Printf("  %-20s %s\n", styleBold.Render("Active dealers:"), styleGreen.Render(strconv.Itoa(dealers)))
	fmt.Printf("  %-20s %s\n", styleBold.Render("Total vehicles:"), styleGreen.Render(strconv.Itoa(total)))
	fmt.Printf("  %-20s %s\n", styleBold.Render("Avg quality score:"), scoreStyle(avgScore*100))
	fmt.Println()

	if len(stats) > 0 {
		fmt.Println(styleHeader.Render("BY COUNTRY"))
		fmt.Printf("  %-8s %8s %10s %12s\n",
			styleBold.Render("COUNTRY"),
			styleBold.Render("VEHICLES"),
			styleBold.Render("AVG KM"),
			styleBold.Render("AVG PRICE€"),
		)
		fmt.Println("  " + strings.Repeat("─", 44))
		for _, s := range stats {
			fmt.Printf("  %-8s %8d %10.0f %12.0f\n",
				s.country, s.count, s.avgKm, s.avgEUR)
		}
	}
	fmt.Println()
	return nil
}

// ── Formatting helpers ────────────────────────────────────────────────────────

func field(label, value string) string {
	return fmt.Sprintf("  %-18s %s\n", styleDim.Render(label+":"), value)
}

func scoreStyle(score float64) string {
	s := fmt.Sprintf("%5.1f%%", score)
	switch {
	case score >= 80:
		return styleGreen.Render(s)
	case score >= 60:
		return styleYellow.Render(s)
	default:
		return styleRed.Render(s)
	}
}

// ── Entry point ───────────────────────────────────────────────────────────────

func main() {
	if err := newRootCmd().Execute(); err != nil {
		os.Exit(1)
	}
}
