package kanban

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"time"
)

// ── Kanban types ──────────────────────────────────────────────────────────────

// Column is a Kanban board column (maps 1:1 to a vehicle state).
type Column struct {
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	Name         string `json:"name"`
	Position     int    `json:"position"`
	Color        string `json:"color"`
	VehicleLimit int    `json:"vehicle_limit"`
	IsDefault    bool   `json:"is_default"`
	StateKey     string `json:"state_key,omitempty"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	Cards        []Card `json:"cards,omitempty"`
}

// Card is a vehicle's representation on the board.
type Card struct {
	VehicleID  string   `json:"vehicle_id"`
	TenantID   string   `json:"tenant_id"`
	ColumnID   string   `json:"column_id"`
	Position   int      `json:"position"`
	AssigneeID string   `json:"assignee_id,omitempty"`
	Priority   string   `json:"priority"`
	Labels     []string `json:"labels"`
	DueDate    string   `json:"due_date,omitempty"`
	UpdatedAt  string   `json:"updated_at"`
}

// MoveRequest is the body for PUT /kanban/cards/{vehicleId}/move.
type MoveRequest struct {
	TargetColumnID string `json:"target_column_id"`
	Position       int    `json:"position"`
}

// CardPatch is the body for PUT /kanban/cards/{vehicleId}.
type CardPatch struct {
	AssigneeID *string  `json:"assignee_id,omitempty"`
	Priority   *string  `json:"priority,omitempty"`
	Labels     []string `json:"labels,omitempty"`
	DueDate    *string  `json:"due_date,omitempty"`
}

// ColumnPatch is the body for PUT /kanban/columns/{id}.
type ColumnPatch struct {
	Name         *string `json:"name,omitempty"`
	Color        *string `json:"color,omitempty"`
	VehicleLimit *int    `json:"vehicle_limit,omitempty"`
}

// ── Calendar types ────────────────────────────────────────────────────────────

// Event is a calendar entry.
type Event struct {
	ID              string `json:"id"`
	TenantID        string `json:"tenant_id"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	EventType       string `json:"event_type"`
	VehicleID       string `json:"vehicle_id,omitempty"`
	ContactID       string `json:"contact_id,omitempty"`
	DealID          string `json:"deal_id,omitempty"`
	StartAt         string `json:"start_at"`
	EndAt           string `json:"end_at"`
	AllDay          bool   `json:"all_day"`
	Location        string `json:"location"`
	AssigneeID      string `json:"assignee_id,omitempty"`
	Status          string `json:"status"`
	ReminderMinutes int    `json:"reminder_minutes"`
	AutoGenerated   bool   `json:"auto_generated"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

// EventPatch is used for PUT /calendar/events/{id}.
type EventPatch struct {
	Title           *string `json:"title,omitempty"`
	Description     *string `json:"description,omitempty"`
	StartAt         *string `json:"start_at,omitempty"`
	EndAt           *string `json:"end_at,omitempty"`
	AllDay          *bool   `json:"all_day,omitempty"`
	Location        *string `json:"location,omitempty"`
	AssigneeID      *string `json:"assignee_id,omitempty"`
	Status          *string `json:"status,omitempty"`
	ReminderMinutes *int    `json:"reminder_minutes,omitempty"`
}

// ── State machine ─────────────────────────────────────────────────────────────

// validTransitions defines allowed vehicle state transitions.
var validTransitions = map[string][]string{
	"sourcing":       {"acquired"},
	"acquired":       {"reconditioning", "listed"},
	"reconditioning": {"photography", "listed"},
	"photography":    {"listed"},
	"listed":         {"inquiry", "reserved", "sold"},
	"inquiry":        {"negotiation", "listed"},
	"negotiation":    {"reserved", "inquiry"},
	"reserved":       {"sold", "negotiation"},
	"sold":           {"in_transit"},
	"in_transit":     {"delivered"},
	"delivered":      {},
}

// ValidateTransition returns an error if from→to is not allowed.
func ValidateTransition(from, to string) error {
	allowed, ok := validTransitions[from]
	if !ok {
		return fmt.Errorf("unknown state %q", from)
	}
	for _, a := range allowed {
		if a == to {
			return nil
		}
	}
	return fmt.Errorf("transition %q → %q is not allowed", from, to)
}

// ValidPriorities lists accepted card priorities.
var ValidPriorities = map[string]bool{
	"low": true, "normal": true, "high": true, "urgent": true,
}

// ValidEventTypes lists accepted event types.
var ValidEventTypes = map[string]bool{
	"transport_pickup":    true,
	"transport_delivery":  true,
	"inspection":          true,
	"photography":         true,
	"client_meeting":      true,
	"auction":             true,
	"registration":        true,
	"other":               true,
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func newID() string {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}

func nowRFC3339() string {
	return time.Now().UTC().Format(time.RFC3339)
}

func addDays(from string, days int) string {
	t, err := time.Parse(time.RFC3339, from)
	if err != nil {
		t = time.Now().UTC()
	}
	return t.Add(time.Duration(days) * 24 * time.Hour).Format(time.RFC3339)
}
