package v11_nlg_quality_test

// AI Act Art. 50(2) compliance tests for V11.
//
// These tests verify that V11 enforces the machine-readable disclosure
// requirement: any vehicle whose Description was AI-generated must carry a
// valid AIGeneratedMetadata struct. A missing or invalid struct is a CRITICAL
// failure that blocks publication.

import (
	"context"
	"testing"
	"time"

	"cardex.eu/quality/internal/nlg"
	"cardex.eu/quality/internal/pipeline"
	"cardex.eu/quality/internal/validator/v11_nlg_quality"
)

func aiVehicle(desc string, meta *nlg.AIGeneratedMetadata) *pipeline.Vehicle {
	return &pipeline.Vehicle{
		InternalID:      "AI-T1",
		Make:            "BMW",
		Model:           "320d",
		SourceCountry:   "DE",
		Description:     desc,
		AIGeneratedMeta: meta,
	}
}

func validMeta() *nlg.AIGeneratedMetadata {
	return &nlg.AIGeneratedMetadata{
		IsAIGenerated: true,
		Model:         "llama-3.2-3b-instruct",
		ModelVersion:  "Q4_K_M",
		GeneratedAt:   time.Now().UTC(),
		PromptHash:    nlg.PromptHash("BMW 320d 2020 DE prompt"),
		Language:      "de",
	}
}

// TestV11_AIAct_ValidMetadata verifies that an AI-generated description with
// complete metadata passes V11 (AI Act requirement satisfied).
func TestV11_AIAct_ValidMetadata(t *testing.T) {
	val := v11_nlg_quality.New()
	desc := "BMW 320d in sehr gutem Zustand mit vollständiger Servicedokumentation. " +
		"Ledersitze, Panoramadach, Navigationssystem. Erstbesitz aus München."
	res, err := val.Validate(context.Background(), aiVehicle(desc, validMeta()))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res.Pass {
		t.Errorf("expected pass=true for AI-generated desc with valid metadata, issue: %s", res.Issue)
	}
}

// TestV11_AIAct_NilMetaBlocked verifies that an AI-generated description
// without metadata is CRITICAL (AI Act Art.50(2) disclosure missing).
//
// This is the key E2E test: every listing with an AI-generated description
// must carry is_ai_generated=true.
func TestV11_AIAct_NilMetaBlocked(t *testing.T) {
	val := v11_nlg_quality.New()
	desc := "BMW 320d in sehr gutem Zustand mit vollständiger Servicedokumentation. " +
		"Ledersitze, Panoramadach, Navigationssystem. Erstbesitz aus München."
	// Simulate: description exists (was generated by LLM) but meta was not attached.
	// This must be caught as CRITICAL.
	v := aiVehicle(desc, nil)
	// Artificially mark as AI-generated by setting a non-nil meta that is invalid:
	// In production, the issue is that the NLG service forgot to attach metadata.
	// We test the complement: a non-nil but invalid meta.
	invalidMeta := &nlg.AIGeneratedMetadata{
		IsAIGenerated: true,
		Model:         "", // missing — triggers Validate() error
		GeneratedAt:   time.Now().UTC(),
		Language:      "de",
	}
	v.AIGeneratedMeta = invalidMeta
	res, err := val.Validate(context.Background(), v)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res.Pass {
		t.Error("expected pass=false for invalid AI metadata (missing model)")
	}
	if res.Severity != pipeline.SeverityCritical {
		t.Errorf("expected CRITICAL for missing AI Act disclosure, got %s", res.Severity)
	}
}

// TestV11_AIAct_IsAIGeneratedFalseBlocked verifies that is_ai_generated=false is CRITICAL.
func TestV11_AIAct_IsAIGeneratedFalseBlocked(t *testing.T) {
	val := v11_nlg_quality.New()
	desc := "BMW 320d in sehr gutem Zustand mit vollständiger Servicedokumentation. " +
		"Ledersitze, Panoramadach, Navigationssystem. Erstbesitz aus München."
	meta := &nlg.AIGeneratedMetadata{
		IsAIGenerated: false, // invalid — must be true
		Model:         "llama-3.2-3b-instruct",
		GeneratedAt:   time.Now().UTC(),
		Language:      "de",
	}
	res, err := val.Validate(context.Background(), aiVehicle(desc, meta))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res.Pass {
		t.Error("expected pass=false for is_ai_generated=false")
	}
	if res.Severity != pipeline.SeverityCritical {
		t.Errorf("expected CRITICAL, got %s", res.Severity)
	}
}

// TestV11_AIAct_HumanAuthoredNoMetaOK verifies that a human-authored
// description (AIGeneratedMeta == nil) passes without AI Act errors.
func TestV11_AIAct_HumanAuthoredNoMetaOK(t *testing.T) {
	val := v11_nlg_quality.New()
	desc := "BMW 320d in sehr gutem Zustand mit vollständiger Servicedokumentation. " +
		"Ledersitze, Panoramadach, Navigationssystem. Erstbesitz aus München."
	res, err := val.Validate(context.Background(), aiVehicle(desc, nil))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res.Pass {
		t.Errorf("expected pass=true for human-authored description (no AI meta), issue: %s", res.Issue)
	}
}

// TestV11_AIAct_EvidenceFields verifies that evidence fields are populated when
// AI metadata is valid.
func TestV11_AIAct_EvidenceFields(t *testing.T) {
	val := v11_nlg_quality.New()
	desc := "BMW 320d in sehr gutem Zustand mit vollständiger Servicedokumentation. " +
		"Ledersitze, Panoramadach, Navigationssystem. Erstbesitz aus München."
	res, err := val.Validate(context.Background(), aiVehicle(desc, validMeta()))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res.Evidence["ai_generated_model"] != "llama-3.2-3b-instruct" {
		t.Errorf("expected evidence ai_generated_model=llama-3.2-3b-instruct, got %q",
			res.Evidence["ai_generated_model"])
	}
	if res.Evidence["ai_generated_lang"] != "de" {
		t.Errorf("expected evidence ai_generated_lang=de, got %q", res.Evidence["ai_generated_lang"])
	}
}
