"""
Config-driven extraction — the per-portal recipe lives in a versioned store, not code.

Today each portal hardcodes its extraction recipe as class attributes
(``HOST``/``DETAIL_RE``/``PAGE_SIZE``/``MAX_PAGES`` in ``portals/<x>/__init__.py``).
That couples "what to extract / how" to a Python edit + redeploy. This module
externalises that recipe to a **versioned JSON store** (``configs/portals/*.json``,
tracked in git → every change is a reviewable diff) so the day a portal changes its
HTML the fix is a config edit on ONE file, not a code change.

An ``ExtractionConfig`` captures the five axes the addendum names:
  strategy · endpoints · pagination · extraction/normalization · drift baseline.

The ``drift_baseline`` block is the seed of the anti-breakage resilience subsystem
(see ``scrapers/intelligence/drift_gate.py``): expected volume, required fields, and
the extraction method whose schema fingerprint (``intelligence/schema.py``) is
tracked. When a harvest deviates from the baseline, drift is detected, alerted by
source, and repaired by editing this config — never by silently ingesting garbage.

This is the contract; migrating every portal to *execute* purely from config is a
follow-up (the classes can ``load(source_key)`` incrementally). The store and the
drift baseline are live now so the NL pattern is born config-driven.
"""
from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field, fields as dataclass_fields, replace
from pathlib import Path

# Versioned store root — git-tracked JSON, one file per source_key.
# (Path("") is truthy as Path("."), so test the env string explicitly.)
_ENV_DIR = os.environ.get("CARDEX_PORTAL_CONFIG_DIR", "").strip()
_CONFIG_DIR = Path(_ENV_DIR) if _ENV_DIR else (
    Path(__file__).resolve().parents[2] / "configs" / "portals"
)

# Dealer configs are AUTO-GENERATED by the per-dealer detector (frente C) and kept
# in a SEPARATE store so the curated portal recipes and the ~30k-scale dealer
# long-tail never collide. ``load()`` searches portals first (curated wins), then
# dealers — so the seam's config-driven routing (``enrich_worker._is_playwright_source``)
# resolves a dealer's recipe with ZERO change to the seam.
_DEALER_ENV_DIR = os.environ.get("CARDEX_DEALER_CONFIG_DIR", "").strip()
_DEALER_DIR = Path(_DEALER_ENV_DIR) if _DEALER_ENV_DIR else (
    Path(__file__).resolve().parents[2] / "configs" / "dealers"
)

# Family recipes are PARAMETRIC: one recipe per web platform/CMS (the family key
# is ``cms_fingerprint.CmsVerdict.cms``, e.g. 'wordpress', 'dealer_com'), with NO
# concrete host inside. ``instantiate_family`` fills a dealer's host into the
# platform's endpoint patterns at resolve time. This is the CMS multiplier:
# one verified family recipe serves EVERY dealer built on that platform, so this
# store scales with the number of platforms, not with the ~30k dealer long-tail.
_FAMILY_ENV_DIR = os.environ.get("CARDEX_FAMILY_CONFIG_DIR", "").strip()
_FAMILY_DIR = Path(_FAMILY_ENV_DIR) if _FAMILY_ENV_DIR else (
    Path(__file__).resolve().parents[2] / "configs" / "families"
)

# Recognised extraction strategies (how the source exposes its inventory).
STRATEGIES = (
    "portal_paginated",   # search/listing pages with N-page pagination (autotrack)
    "sitemap_listing",    # sitemap-first deep-link discovery (SitemapListingScraper)
    "jsonld_detail",      # detail pages carry schema.org Car/Vehicle JSON-LD
    "wp_rest",            # WordPress /wp-json CPT enumeration (dealer long-tail)
    "socrata",            # open-data Socrata API (discovery, e.g. RDW)
    "playwright_meta",    # E07: JS/SPA — render in a browser, parse SEO meta (autolina)
    "playwright_xhr",     # E07: JS/SPA — render + intercept the SPA's data XHR/JSON
    "faceted_ssr",        # T1 anti-bot SSR walked by year×price facets to beat the
                          # hard result cap (autoscout24.de, coches.net, lacentrale.fr)
)

# Strategies that require the browser renderer (E07). A source with one of these
# routes through the Playwright extractor instead of the static fetch cascade.
PLAYWRIGHT_STRATEGIES = ("playwright_meta", "playwright_xhr")


@dataclass(frozen=True)
class Endpoints:
    """Where to fetch. Only the fields a given strategy needs are set."""

    host: str = ""
    listing_url_template: str = ""   # e.g. "https://www.autotrack.nl/aanbod?pageNumber={page}"
    sitemap_url: str = ""
    detail_url_re: str = ""          # regex isolating a vehicle detail deep-link
    api_url: str = ""                # socrata / wp-rest / dealer DMS feed


@dataclass(frozen=True)
class Pagination:
    """How to walk the listing surface."""

    page_size: int = 0
    max_pages: int = 0
    page_param: str = "page"
    cap_results: int = 0             # hard per-query ceiling (faceting must split below it)


@dataclass(frozen=True)
class Extraction:
    """How to turn a fetched page into canonical fields (normalization)."""

    method: str = "jsonld"           # jsonld | microdata | og | heuristic | socrata
    # canonical_field -> source path/selector/key. Empty = use pipeline.parse defaults.
    field_map: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class DriftBaseline:
    """
    The anti-breakage contract for a source — what a healthy harvest looks like.

    A harvest that drops below ``expected_min_volume``, or whose records fall below
    ``min_nonnull_ratio`` on ``required_fields``, or whose extraction-schema
    fingerprint shifts, is DRIFT: alert by source, pause, repair this config.
    """

    extraction_method: str = "jsonld"
    expected_min_volume: int = 1          # min listings a healthy cycle yields
    required_fields: tuple[str, ...] = ("make", "model", "year", "price")
    min_nonnull_ratio: float = 0.7        # fraction of records carrying every required field


@dataclass(frozen=True)
class ExtractionConfig:
    """The full, versioned extraction recipe for one source_key."""

    source_key: str
    country: str
    strategy: str
    version: int = 1
    endpoints: Endpoints = field(default_factory=Endpoints)
    pagination: Pagination = field(default_factory=Pagination)
    extraction: Extraction = field(default_factory=Extraction)
    drift_baseline: DriftBaseline = field(default_factory=DriftBaseline)

    def __post_init__(self) -> None:
        if self.strategy not in STRATEGIES:
            raise ValueError(f"unknown strategy {self.strategy!r} (one of {STRATEGIES})")
        if not self.source_key or not self.country:
            raise ValueError("source_key and country are required")


@dataclass(frozen=True)
class FamilyMatch:
    """Which fingerprint verdicts a family recipe claims to cover."""

    cms: str = ""                    # cms_fingerprint family key this recipe serves
    min_confidence: str = "medium"   # 'medium' | 'high' (cms_fingerprint scale)


@dataclass(frozen=True)
class FamilyEndpoints:
    """
    Host-INDEPENDENT endpoint patterns of a platform/CMS.

    No field carries a concrete dealer host — ``instantiate_family`` combines
    these patterns with a host into a concrete ``Endpoints`` at resolve time.
    """

    sitemap_hint: str = ""                       # path → endpoints.sitemap_url
    catalog_path_tokens: tuple[str, ...] = ()    # first token → listing_url_template
    detail_url_re: str = ""                      # host-independent detail deep-link regex
    api_path_hint: str = ""                      # path → endpoints.api_url (e.g. wp_rest)


@dataclass(frozen=True)
class Provenance:
    """Honest verification trail — which REAL dealers proved this family recipe."""

    verified_on_dealers: tuple[str, ...] = ()
    verified_count: int = 0
    verified_date: str | None = None
    tool: str = ""


# Confidence ladder shared with cms_fingerprint ('unknown' < 'medium' < 'high').
_CONFIDENCE_RANK = {"unknown": 0, "medium": 1, "high": 2}


@dataclass(frozen=True)
class FamilyRecipe:
    """
    A parametric extraction recipe for a whole platform family (no host inside).

    One file per CMS in ``configs/families/<cms>.json``. Instantiated per dealer
    via ``instantiate_family`` — the multiplier "1 recipe = N sites of the same
    platform". ``provenance`` records which real dealers proved the recipe.
    """

    family_key: str
    strategy: str
    kind: str = "family"
    version: int = 1
    matches: FamilyMatch = field(default_factory=FamilyMatch)
    endpoints: FamilyEndpoints = field(default_factory=FamilyEndpoints)
    extraction: Extraction = field(default_factory=Extraction)
    drift_baseline: DriftBaseline = field(default_factory=DriftBaseline)
    provenance: Provenance = field(default_factory=Provenance)

    def __post_init__(self) -> None:
        if self.strategy not in STRATEGIES:
            raise ValueError(f"unknown strategy {self.strategy!r} (one of {STRATEGIES})")
        if not self.family_key:
            raise ValueError("family_key is required")

    def accepts(self, cms: str, confidence: str = "medium") -> bool:
        """True when a fingerprint verdict ``(cms, confidence)`` is covered by
        this recipe's ``matches`` block (cms equal, confidence at/above floor)."""
        if self.matches.cms and self.matches.cms != cms:
            return False
        floor = _CONFIDENCE_RANK.get(self.matches.min_confidence, 1)
        return _CONFIDENCE_RANK.get(confidence, 0) >= floor


def _config_path(source_key: str) -> Path:
    # source_key is a domain ("autotrack.nl") → flat file name.
    safe = source_key.replace("/", "_")
    return _CONFIG_DIR / f"{safe}.json"


def _dealer_path(source_key: str) -> Path:
    """
    Path of a source's config in the auto-generated dealer store.

    ``source_key`` is a ``discovery_candidates.domain`` (external/untrusted). Beyond the
    ``/`` → ``_`` flattening, resolve the path and reject anything that escapes the store
    dir — defense-in-depth against a hostile ``..``-bearing domain value.
    """
    safe = source_key.replace("/", "_")
    p = (_DEALER_DIR / f"{safe}.json").resolve()
    if not p.is_relative_to(_DEALER_DIR.resolve()):
        raise ValueError(f"path traversal rejected for source_key {source_key!r}")
    return p


def _family_path(cms: str) -> Path:
    """
    Path of a family recipe in the per-CMS store.

    The family key normally comes from ``cms_fingerprint`` (a controlled
    vocabulary), but apply the same traversal defense as ``_dealer_path`` —
    defense-in-depth against a hostile ``..``-bearing key reaching this layer.
    """
    safe = cms.replace("/", "_")
    p = (_FAMILY_DIR / f"{safe}.json").resolve()
    if not p.is_relative_to(_FAMILY_DIR.resolve()):
        raise ValueError(f"path traversal rejected for family key {cms!r}")
    return p


def _only(cls, d: dict) -> dict:
    """Keep only keys that are real fields of ``cls`` — free-form annotation keys
    (e.g. a ``note`` documenting a hard cap) live in the JSON for humans but must
    not break the splat into a frozen dataclass."""
    known = {f.name for f in dataclass_fields(cls)}
    return {k: v for k, v in (d or {}).items() if k in known}


def from_dict(d: dict) -> ExtractionConfig:
    """Build an ExtractionConfig from a parsed JSON dict (tolerant of missing blocks
    and of human-annotation keys like ``note`` that are not dataclass fields)."""
    drift = _only(DriftBaseline, d.get("drift_baseline", {}))
    if "required_fields" in drift:
        drift["required_fields"] = tuple(drift["required_fields"])
    return ExtractionConfig(
        source_key=d["source_key"],
        country=d["country"],
        strategy=d["strategy"],
        version=int(d.get("version", 1)),
        endpoints=Endpoints(**_only(Endpoints, d.get("endpoints", {}))),
        pagination=Pagination(**_only(Pagination, d.get("pagination", {}))),
        extraction=Extraction(**_only(Extraction, d.get("extraction", {}))),
        drift_baseline=DriftBaseline(**drift),
    )


def to_dict(cfg: ExtractionConfig) -> dict:
    """Serialise a config to a JSON-ready dict (tuples → lists)."""
    d = asdict(cfg)
    d["drift_baseline"]["required_fields"] = list(cfg.drift_baseline.required_fields)
    return d


def family_from_dict(d: dict) -> FamilyRecipe:
    """Build a FamilyRecipe from a parsed JSON dict (tolerant of missing blocks
    and of human-annotation keys, exactly like ``from_dict``)."""
    drift = _only(DriftBaseline, d.get("drift_baseline", {}))
    if "required_fields" in drift:
        drift["required_fields"] = tuple(drift["required_fields"])
    ep = _only(FamilyEndpoints, d.get("endpoints", {}))
    if "catalog_path_tokens" in ep:
        ep["catalog_path_tokens"] = tuple(ep["catalog_path_tokens"])
    prov = _only(Provenance, d.get("provenance", {}))
    if "verified_on_dealers" in prov:
        prov["verified_on_dealers"] = tuple(prov["verified_on_dealers"])
    return FamilyRecipe(
        family_key=d["family_key"],
        strategy=d["strategy"],
        kind=d.get("kind", "family"),
        version=int(d.get("version", 1)),
        matches=FamilyMatch(**_only(FamilyMatch, d.get("matches", {}))),
        endpoints=FamilyEndpoints(**ep),
        extraction=Extraction(**_only(Extraction, d.get("extraction", {}))),
        drift_baseline=DriftBaseline(**drift),
        provenance=Provenance(**prov),
    )


def family_to_dict(recipe: FamilyRecipe) -> dict:
    """Serialise a family recipe to a JSON-ready dict (tuples → lists)."""
    d = asdict(recipe)
    d["endpoints"]["catalog_path_tokens"] = list(recipe.endpoints.catalog_path_tokens)
    d["drift_baseline"]["required_fields"] = list(recipe.drift_baseline.required_fields)
    d["provenance"]["verified_on_dealers"] = list(recipe.provenance.verified_on_dealers)
    return d


def load_family(cms: str) -> FamilyRecipe | None:
    """Load the family recipe for a CMS key, or None when none exists."""
    path = _family_path(cms)
    if not path.exists():
        return None
    return family_from_dict(json.loads(path.read_text(encoding="utf-8")))


def save_family(recipe: FamilyRecipe) -> Path:
    """Persist a family recipe to the per-CMS store (creates the dir on first write)."""
    path = _family_path(recipe.family_key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(family_to_dict(recipe), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return path


# host TLD → ISO-2 country for the six CARDEX countries; anything else maps to
# the ISO 3166-1 user-assigned 'ZZ' (country unknown) — honest, never invented.
_TLD_COUNTRY = {"nl": "NL", "de": "DE", "es": "ES", "fr": "FR", "be": "BE", "ch": "CH"}
_UNKNOWN_COUNTRY = "ZZ"


def _normalize_host(host: str) -> str:
    """Bare lowercase hostname: scheme and any path/trailing slash stripped."""
    h = host.strip().lower()
    for scheme in ("https://", "http://"):
        if h.startswith(scheme):
            h = h[len(scheme):]
    return h.split("/", 1)[0]


def _country_from_tld(domain: str) -> str:
    return _TLD_COUNTRY.get(domain.rsplit(".", 1)[-1], _UNKNOWN_COUNTRY)


def _abs_path(path: str) -> str:
    return path if path.startswith("/") else f"/{path}"


def instantiate_family(
    recipe: FamilyRecipe, host: str, *, country: str = ""
) -> ExtractionConfig:
    """
    Fill a dealer's host into a family recipe → a concrete, usable ExtractionConfig.

    The platform's host-independent patterns become per-dealer endpoints:
      * ``sitemap_hint``            → ``sitemap_url = https://<host><hint>``
      * first ``catalog_path_token``→ ``listing_url_template = https://<host>/<token>``
      * ``api_path_hint``           → ``api_url = https://<host><hint>``
      * ``detail_url_re``           → copied as-is (already host-independent)

    ``source_key`` is the host minus any leading ``www.`` (the canonical
    discovery domain form); ``country`` falls back to the host TLD, else 'ZZ'.
    The instantiated config is NOT persisted — it is a resolve-time view, so the
    family file stays the single point of repair for the whole platform.
    """
    h = _normalize_host(host)
    if not h:
        raise ValueError("host is required to instantiate a family recipe")
    source_key = h[4:] if h.startswith("www.") else h
    base = f"https://{h}"
    fe = recipe.endpoints
    tokens = tuple(t.strip("/") for t in fe.catalog_path_tokens if t.strip("/"))
    return ExtractionConfig(
        source_key=source_key,
        country=country or _country_from_tld(source_key),
        strategy=recipe.strategy,
        version=recipe.version,
        endpoints=Endpoints(
            host=h,
            listing_url_template=f"{base}/{tokens[0]}" if tokens else "",
            sitemap_url=f"{base}{_abs_path(fe.sitemap_hint)}" if fe.sitemap_hint else "",
            detail_url_re=fe.detail_url_re,
            api_url=f"{base}{_abs_path(fe.api_path_hint)}" if fe.api_path_hint else "",
        ),
        extraction=recipe.extraction,
        drift_baseline=recipe.drift_baseline,
    )


def load(
    source_key: str, *, cms: str | None = None, country: str = ""
) -> ExtractionConfig | None:
    """
    Load a source's versioned config, or None when no config file exists.

    Resolution order: curated portal store FIRST, then the auto-generated dealer
    store — a hand-tuned portal recipe always wins over a detector-generated one
    and the seam (``enrich_worker``) has a single routing lookup for portals and
    dealers alike. When ``cms`` is given (the dealer's known platform family from
    ``cms_fingerprint``) and neither per-source store has a recipe, the family
    recipe for that CMS is instantiated with ``source_key`` as the host —
    the "1 recipe = N dealers" multiplier. ``cms=None`` (the default) keeps the
    behaviour identical to the pre-family resolver. ``country`` only feeds the
    family instantiation (per-source recipes already carry their country).
    """
    for path in (_config_path(source_key), _dealer_path(source_key)):
        if path.exists():
            return from_dict(json.loads(path.read_text(encoding="utf-8")))
    if cms:
        recipe = load_family(cms)
        if recipe is not None:
            return instantiate_family(recipe, source_key, country=country)
    return None


def is_minimal_auto(cfg: ExtractionConfig) -> bool:
    """True for a detector/cage-built MINIMAL recipe — one carrying no operator tuning.

    Minimal = no ``detail_url_re``, no ``field_map``, no ``api_url``: exactly what the
    generic-cascade save materializes. A family recipe accepted by a live CMS verdict
    may outrank these (the platform walk beats a blind cascade); a recipe with ANY of
    those fields is treated as tuned and always wins (never clobber a human's repair).
    """
    return (not (cfg.endpoints.detail_url_re or "").strip()
            and not cfg.extraction.field_map
            and not (cfg.endpoints.api_url or "").strip())


def save(cfg: ExtractionConfig, *, kind: str = "portal") -> Path:
    """
    Persist a config to the versioned store (creates the dir on first write).

    ``kind="dealer"`` targets the auto-generated dealer store; the default
    ``"portal"`` keeps the curated store and every existing caller unchanged.
    """
    path = _dealer_path(cfg.source_key) if kind == "dealer" else _config_path(cfg.source_key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(to_dict(cfg), indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def emit(cfg: ExtractionConfig, *, kind: str = "dealer") -> ExtractionConfig:
    """
    Emit a recipe on a verified extraction success — CREATE-IF-ABSENT, never clobber.

    Recipes are git-tracked and hand-tuned to repair drift, so an emit on a source that
    already has one must NOT overwrite operator/curation edits (strategy, endpoints incl.
    ``detail_url_re``, field_map). It only (a) version-bumps and (b) raises the learned
    drift floor ``expected_min_volume`` to the freshly proven volume (never lowers it — a
    transient under-discovery must not erase a known-good baseline). The first emit of an
    unseen source writes ``cfg`` as-is (version 1). Returns the config actually persisted.

    This is the Bloque-D recipe contract: every 100%-successful scrape leaves a versioned,
    individually-manageable recipe, without ever clobbering a human's repair.
    """
    path = _dealer_path(cfg.source_key) if kind == "dealer" else _config_path(cfg.source_key)
    prior = from_dict(json.loads(path.read_text(encoding="utf-8"))) if path.exists() else None
    if prior is None:
        save(cfg, kind=kind)
        return cfg
    new_floor = max(
        prior.drift_baseline.expected_min_volume, cfg.drift_baseline.expected_min_volume
    )
    merged = replace(
        prior,
        version=prior.version + 1,
        drift_baseline=replace(prior.drift_baseline, expected_min_volume=new_floor),
    )
    save(merged, kind=kind)
    return merged


def list_configs(kind: str = "portal") -> list[str]:
    """
    Every source_key with a versioned config (sorted).

    ``kind`` selects the store: ``"portal"`` (default, curated), ``"dealer"``
    (auto-generated), ``"family"`` (per-CMS parametric recipes — note these keys
    are CMS family names, NOT source_keys), or ``"all"`` (union of the two
    per-source stores, deduplicated; families are a different key namespace and
    are deliberately excluded).
    """
    dirs = {
        "portal": (_CONFIG_DIR,),
        "dealer": (_DEALER_DIR,),
        "family": (_FAMILY_DIR,),
        "all": (_CONFIG_DIR, _DEALER_DIR),
    }.get(kind, (_CONFIG_DIR,))
    keys: set[str] = set()
    for d in dirs:
        if d.exists():
            keys.update(p.stem for p in d.glob("*.json"))
    return sorted(keys)
