"""
Config-driven extraction — the per-portal recipe lives in a versioned store, not code.

Today each portal hardcodes its extraction recipe as class attributes
(``HOST``/``DETAIL_RE``/``PAGE_SIZE``/``MAX_PAGES`` in ``portals/<x>/__init__.py``).
That couples "what to extract / how" to a Python edit + redeploy. This module
externalises that recipe to a **versioned JSON store** (``configs/portals/*.json``,
tracked in git → every change is a reviewable diff) so the day a portal changes its
HTML the fix is a config edit on ONE file, not a code change.

An ``ExtractionConfig`` captures the five axes the addendum names:
  strategy · endpoints · pagination · extraction/normalization · drift baseline.

The ``drift_baseline`` block is the seed of the anti-breakage resilience subsystem
(see ``scrapers/intelligence/drift_gate.py``): expected volume, required fields, and
the extraction method whose schema fingerprint (``intelligence/schema.py``) is
tracked. When a harvest deviates from the baseline, drift is detected, alerted by
source, and repaired by editing this config — never by silently ingesting garbage.

This is the contract; migrating every portal to *execute* purely from config is a
follow-up (the classes can ``load(source_key)`` incrementally). The store and the
drift baseline are live now so the NL pattern is born config-driven.
"""
from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field, fields as dataclass_fields, replace
from pathlib import Path

# Versioned store root — git-tracked JSON, one file per source_key.
# (Path("") is truthy as Path("."), so test the env string explicitly.)
_ENV_DIR = os.environ.get("CARDEX_PORTAL_CONFIG_DIR", "").strip()
_CONFIG_DIR = Path(_ENV_DIR) if _ENV_DIR else (
    Path(__file__).resolve().parents[2] / "configs" / "portals"
)

# Dealer configs are AUTO-GENERATED by the per-dealer detector (frente C) and kept
# in a SEPARATE store so the curated portal recipes and the ~30k-scale dealer
# long-tail never collide. ``load()`` searches portals first (curated wins), then
# dealers — so the seam's config-driven routing (``enrich_worker._is_playwright_source``)
# resolves a dealer's recipe with ZERO change to the seam.
_DEALER_ENV_DIR = os.environ.get("CARDEX_DEALER_CONFIG_DIR", "").strip()
_DEALER_DIR = Path(_DEALER_ENV_DIR) if _DEALER_ENV_DIR else (
    Path(__file__).resolve().parents[2] / "configs" / "dealers"
)

# Recognised extraction strategies (how the source exposes its inventory).
STRATEGIES = (
    "portal_paginated",   # search/listing pages with N-page pagination (autotrack)
    "sitemap_listing",    # sitemap-first deep-link discovery (SitemapListingScraper)
    "jsonld_detail",      # detail pages carry schema.org Car/Vehicle JSON-LD
    "wp_rest",            # WordPress /wp-json CPT enumeration (dealer long-tail)
    "socrata",            # open-data Socrata API (discovery, e.g. RDW)
    "playwright_meta",    # E07: JS/SPA — render in a browser, parse SEO meta (autolina)
    "playwright_xhr",     # E07: JS/SPA — render + intercept the SPA's data XHR/JSON
    "faceted_ssr",        # T1 anti-bot SSR walked by year×price facets to beat the
                          # hard result cap (autoscout24.de, coches.net, lacentrale.fr)
)

# Strategies that require the browser renderer (E07). A source with one of these
# routes through the Playwright extractor instead of the static fetch cascade.
PLAYWRIGHT_STRATEGIES = ("playwright_meta", "playwright_xhr")


@dataclass(frozen=True)
class Endpoints:
    """Where to fetch. Only the fields a given strategy needs are set."""

    host: str = ""
    listing_url_template: str = ""   # e.g. "https://www.autotrack.nl/aanbod?pageNumber={page}"
    sitemap_url: str = ""
    detail_url_re: str = ""          # regex isolating a vehicle detail deep-link
    api_url: str = ""                # socrata / wp-rest / dealer DMS feed


@dataclass(frozen=True)
class Pagination:
    """How to walk the listing surface."""

    page_size: int = 0
    max_pages: int = 0
    page_param: str = "page"
    cap_results: int = 0             # hard per-query ceiling (faceting must split below it)


@dataclass(frozen=True)
class Extraction:
    """How to turn a fetched page into canonical fields (normalization)."""

    method: str = "jsonld"           # jsonld | microdata | og | heuristic | socrata
    # canonical_field -> source path/selector/key. Empty = use pipeline.parse defaults.
    field_map: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class DriftBaseline:
    """
    The anti-breakage contract for a source — what a healthy harvest looks like.

    A harvest that drops below ``expected_min_volume``, or whose records fall below
    ``min_nonnull_ratio`` on ``required_fields``, or whose extraction-schema
    fingerprint shifts, is DRIFT: alert by source, pause, repair this config.
    """

    extraction_method: str = "jsonld"
    expected_min_volume: int = 1          # min listings a healthy cycle yields
    required_fields: tuple[str, ...] = ("make", "model", "year", "price")
    min_nonnull_ratio: float = 0.7        # fraction of records carrying every required field


@dataclass(frozen=True)
class ExtractionConfig:
    """The full, versioned extraction recipe for one source_key."""

    source_key: str
    country: str
    strategy: str
    version: int = 1
    endpoints: Endpoints = field(default_factory=Endpoints)
    pagination: Pagination = field(default_factory=Pagination)
    extraction: Extraction = field(default_factory=Extraction)
    drift_baseline: DriftBaseline = field(default_factory=DriftBaseline)

    def __post_init__(self) -> None:
        if self.strategy not in STRATEGIES:
            raise ValueError(f"unknown strategy {self.strategy!r} (one of {STRATEGIES})")
        if not self.source_key or not self.country:
            raise ValueError("source_key and country are required")


def _config_path(source_key: str) -> Path:
    # source_key is a domain ("autotrack.nl") → flat file name.
    safe = source_key.replace("/", "_")
    return _CONFIG_DIR / f"{safe}.json"


def _dealer_path(source_key: str) -> Path:
    """
    Path of a source's config in the auto-generated dealer store.

    ``source_key`` is a ``discovery_candidates.domain`` (external/untrusted). Beyond the
    ``/`` → ``_`` flattening, resolve the path and reject anything that escapes the store
    dir — defense-in-depth against a hostile ``..``-bearing domain value.
    """
    safe = source_key.replace("/", "_")
    p = (_DEALER_DIR / f"{safe}.json").resolve()
    if not p.is_relative_to(_DEALER_DIR.resolve()):
        raise ValueError(f"path traversal rejected for source_key {source_key!r}")
    return p


def _only(cls, d: dict) -> dict:
    """Keep only keys that are real fields of ``cls`` — free-form annotation keys
    (e.g. a ``note`` documenting a hard cap) live in the JSON for humans but must
    not break the splat into a frozen dataclass."""
    known = {f.name for f in dataclass_fields(cls)}
    return {k: v for k, v in (d or {}).items() if k in known}


def from_dict(d: dict) -> ExtractionConfig:
    """Build an ExtractionConfig from a parsed JSON dict (tolerant of missing blocks
    and of human-annotation keys like ``note`` that are not dataclass fields)."""
    drift = _only(DriftBaseline, d.get("drift_baseline", {}))
    if "required_fields" in drift:
        drift["required_fields"] = tuple(drift["required_fields"])
    return ExtractionConfig(
        source_key=d["source_key"],
        country=d["country"],
        strategy=d["strategy"],
        version=int(d.get("version", 1)),
        endpoints=Endpoints(**_only(Endpoints, d.get("endpoints", {}))),
        pagination=Pagination(**_only(Pagination, d.get("pagination", {}))),
        extraction=Extraction(**_only(Extraction, d.get("extraction", {}))),
        drift_baseline=DriftBaseline(**drift),
    )


def to_dict(cfg: ExtractionConfig) -> dict:
    """Serialise a config to a JSON-ready dict (tuples → lists)."""
    d = asdict(cfg)
    d["drift_baseline"]["required_fields"] = list(cfg.drift_baseline.required_fields)
    return d


def load(source_key: str) -> ExtractionConfig | None:
    """
    Load a source's versioned config, or None when no config file exists.

    Searches the curated portal store FIRST, then the auto-generated dealer store,
    so a hand-tuned portal recipe always wins over a detector-generated one and the
    seam (``enrich_worker``) has a single routing lookup for portals and dealers alike.
    """
    for path in (_config_path(source_key), _dealer_path(source_key)):
        if path.exists():
            return from_dict(json.loads(path.read_text(encoding="utf-8")))
    return None


def save(cfg: ExtractionConfig, *, kind: str = "portal") -> Path:
    """
    Persist a config to the versioned store (creates the dir on first write).

    ``kind="dealer"`` targets the auto-generated dealer store; the default
    ``"portal"`` keeps the curated store and every existing caller unchanged.
    """
    path = _dealer_path(cfg.source_key) if kind == "dealer" else _config_path(cfg.source_key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(to_dict(cfg), indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def emit(cfg: ExtractionConfig, *, kind: str = "dealer") -> ExtractionConfig:
    """
    Emit a recipe on a verified extraction success — CREATE-IF-ABSENT, never clobber.

    Recipes are git-tracked and hand-tuned to repair drift, so an emit on a source that
    already has one must NOT overwrite operator/curation edits (strategy, endpoints incl.
    ``detail_url_re``, field_map). It only (a) version-bumps and (b) raises the learned
    drift floor ``expected_min_volume`` to the freshly proven volume (never lowers it — a
    transient under-discovery must not erase a known-good baseline). The first emit of an
    unseen source writes ``cfg`` as-is (version 1). Returns the config actually persisted.

    This is the Bloque-D recipe contract: every 100%-successful scrape leaves a versioned,
    individually-manageable recipe, without ever clobbering a human's repair.
    """
    path = _dealer_path(cfg.source_key) if kind == "dealer" else _config_path(cfg.source_key)
    prior = from_dict(json.loads(path.read_text(encoding="utf-8"))) if path.exists() else None
    if prior is None:
        save(cfg, kind=kind)
        return cfg
    new_floor = max(
        prior.drift_baseline.expected_min_volume, cfg.drift_baseline.expected_min_volume
    )
    merged = replace(
        prior,
        version=prior.version + 1,
        drift_baseline=replace(prior.drift_baseline, expected_min_volume=new_floor),
    )
    save(merged, kind=kind)
    return merged


def list_configs(kind: str = "portal") -> list[str]:
    """
    Every source_key with a versioned config (sorted).

    ``kind`` selects the store: ``"portal"`` (default, curated), ``"dealer"``
    (auto-generated), or ``"all"`` (union of both, deduplicated).
    """
    dirs = {
        "portal": (_CONFIG_DIR,),
        "dealer": (_DEALER_DIR,),
        "all": (_CONFIG_DIR, _DEALER_DIR),
    }.get(kind, (_CONFIG_DIR,))
    keys: set[str] = set()
    for d in dirs:
        if d.exists():
            keys.update(p.stem for p in d.glob("*.json"))
    return sorted(keys)
