-- P1.3b — Convert vehicle_events to monthly RANGE partitions.
--
-- vehicle_events is append-only and unbounded (~2M SEEN/month at scale); a single
-- heap means time-range queries become full scans and idx_ve_hash balloons. This
-- converts it to RANGE-by-month partitions so old months can be detached/dropped
-- and time-range queries prune to one partition.
--
-- SAFETY: run as ONE transaction so any failure — including the row-count verify
-- RAISE at the end — rolls the whole thing back, leaving the original table intact:
--
--     psql --single-transaction -U cardex -d cardex -f scripts/migrate_vehicle_events_partition.sql
--
-- On success the original survives as vehicle_events_old (a backup); drop it
-- manually once you have verified the new table. There must be NO concurrent
-- writer (stop the coordinator / enrich-worker) while this runs.

ALTER TABLE vehicle_events RENAME TO vehicle_events_old;
-- Index names are schema-global: free them from the old table so the new
-- partitioned table can reuse the canonical names. (IF EXISTS: idx_ve_ts may be
-- the interim index added in P1.3a, or absent on a fresh DB.)
ALTER INDEX IF EXISTS vehicle_events_pkey RENAME TO vehicle_events_old_pkey;
ALTER INDEX IF EXISTS idx_ve_hash RENAME TO idx_ve_hash_old;
ALTER INDEX IF EXISTS idx_ve_ts RENAME TO idx_ve_ts_old;

CREATE TABLE vehicle_events (
    event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    url_hash       TEXT NOT NULL,
    url_original   TEXT NOT NULL DEFAULT '',
    source_domain  TEXT NOT NULL DEFAULT '',
    country        CHAR(2) NOT NULL DEFAULT '',
    sitemap_source TEXT NOT NULL DEFAULT '',
    event_type     TEXT NOT NULL CHECK (event_type IN ('SEEN','ENRICHED','GONE')),
    titulo_modelo  TEXT,
    precio         NUMERIC(12,2),
    moneda         CHAR(3) DEFAULT 'EUR',
    kilometraje    INT,
    anio           SMALLINT,
    thumbnail_url  TEXT,
    ts             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- the partition key MUST be in every unique constraint → (event_id, ts)
    PRIMARY KEY (event_id, ts)
) PARTITION BY RANGE (ts);

-- DEFAULT catches any ts with no explicit monthly partition → an insert can never
-- fail for want of a partition (safety net; maintenance pre-creates real months).
CREATE TABLE vehicle_events_default PARTITION OF vehicle_events DEFAULT;
CREATE TABLE vehicle_events_2026_06 PARTITION OF vehicle_events FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE vehicle_events_2026_07 PARTITION OF vehicle_events FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE vehicle_events_2026_08 PARTITION OF vehicle_events FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

-- indexes on the parent propagate to every partition (PG 11+)
CREATE INDEX idx_ve_ts ON vehicle_events (ts);
CREATE INDEX idx_ve_hash ON vehicle_events (url_hash);

INSERT INTO vehicle_events
  (event_id,url_hash,url_original,source_domain,country,sitemap_source,event_type,
   titulo_modelo,precio,moneda,kilometraje,anio,thumbnail_url,ts)
SELECT event_id,url_hash,url_original,source_domain,country,sitemap_source,event_type,
   titulo_modelo,precio,moneda,kilometraje,anio,thumbnail_url,ts
FROM vehicle_events_old;

-- continue the identity sequence past the copied max so new inserts don't collide
SELECT setval(pg_get_serial_sequence('vehicle_events','event_id'),
              GREATEST((SELECT COALESCE(max(event_id),0) FROM vehicle_events), 1));

-- atomic verification: mismatch RAISEs → the whole transaction rolls back
DO $$
DECLARE old_n bigint; new_n bigint;
BEGIN
  SELECT count(*) INTO old_n FROM vehicle_events_old;
  SELECT count(*) INTO new_n FROM vehicle_events;
  IF old_n <> new_n THEN
    RAISE EXCEPTION 'vehicle_events partition migration ROW COUNT MISMATCH: old=% new=%', old_n, new_n;
  END IF;
  RAISE NOTICE 'vehicle_events partition migration OK: % rows preserved', new_n;
END $$;
